/* ============================================================================
 * dms-copy.ts - Notion-editable copy overlay for the DMS page.
 * dms-copy.json is regenerated by scripts/notion/sync-dms-copy.mjs from the
 * "DMS Page Copy" database in Notion (one row per string, matched on Key).
 * Every call site keeps its hardcoded fallback: a deleted or blanked Notion
 * row can never blank the page, it just falls back to the shipped string.
 * ========================================================================== */
import raw from "./dms-copy.json";

type CopySlot = { element: string; text: string };

const COPY = raw as Record<string, CopySlot>;

export function dmsCopy(key: string, fallback: string): string {
  const text = COPY[key]?.text?.trim();
  return text || fallback;
}
