/* ----------------------------------------------------------------------------
 * qms-arcade.tsx - persistent-camera arcade journeys for the QMS page's
 * Notion-backed Product Flows (PF-5, PF-6, PF-7, PF-3: the non-conformance
 * to CAPA arc). Same staging recipe as the DMS journeys: one app window,
 * one world per record, the camera moves between poses and each step's copy
 * is the Notion Flow Step truth restaged, never invented capability.
 * Fictional dataset: Engineering Industries, non-conformance NC-204 (coating
 * thickness, part PRT-4412, line 2) escalating to CAPA-612 from complaint
 * CMP-341. People: J. Rivera (Quality Engineer), M. Osei (Production),
 * S. Okafor (Process Engineering), D. Fontaine (Quality Manager),
 * R. Iyer (CAPA Investigator). Server module, no state.
 * -------------------------------------------------------------------------- */

import {
  type ArcadeFlowWorld,
  type ArcadeStepConfig,
} from "../_shared/arcade/arcade";
import { type HeroArcadeStep } from "../_shared/arcade/hero-arcade";

/* ============================================================ PF-5 world
 * The non-conformance record as the Quality Engineer captures and contains
 * it. Checklist sections are the record's stable anatomy; steps only open
 * sections and advance completion. */
const NC_CAPTURE_WORLD: ArcadeFlowWorld = {
  team: "Engineering Industries",
  recordNoun: "Non-conformance",
  owner: "J. Rivera",
  ownerInitials: "JR",
  participants: ["JR", "MO", "+2"],
  participantsLabel: "J. Rivera, M. Osei, and two others",
  recordKicker: "NON-CONFORMANCE",
  context: {
    initials: "MO",
    name: "M. Osei",
    time: "07:58",
    message: "Coating thickness reading out of spec on line 2.",
    detail: "PRT-4412 housing · WO-8817 · caught at in-process check",
  },
  inboxNeighbors: [
    { title: "Incoming inspection", time: "09:12", detail: "Lot 224-A · sampling due", kind: "Quality event" },
    { title: "Supplier corrective action", time: "Yesterday", detail: "SCAR-31 · evidence requested", kind: "Quality event" },
    { title: "Cleaning validation", time: "Yesterday", detail: "SOP-118 · Rev D effective", kind: "Document" },
  ],
  homeTiles: [
    { label: "Non-conformances", count: 6 },
    { label: "My tasks", count: 4 },
    { label: "Pending approvals", count: 2 },
  ],
  checklistTitle: "Non-conformance",
  checklistSections: [
    {
      title: "CAPTURE & EVIDENCE",
      items: [
        { label: "Photos and measurements", note: "4 photos · 3 readings" },
        { label: "Part and order context", note: "PRT-4412 · WO-8817 · ERP" },
        {
          label: "Problem description",
          kind: "field",
          value: "Coating 38.1 µm on housing face, spec 45-55. Photos 1-4, readings attached.",
          note: "References attached evidence",
        },
      ],
    },
    {
      title: "CONTAINMENT",
      items: [
        { label: "Quarantine lot 118-B", note: "Owner · M. Osei" },
        { label: "Sort remaining WIP", note: "Owner · Line 2" },
        { label: "Hold shipment", note: "Owner · Logistics" },
      ],
    },
    {
      title: "SEVERITY & HISTORY",
      items: [
        { label: "Severity", note: "Major · systemic candidate" },
        { label: "Prior events · PRT-4412", note: "2 in 12 months" },
        { label: "Problem statement", note: "Scopes the investigation" },
      ],
    },
  ],
};

/* ============================================================ PF-6 world
 * The same record NC-204 a day later: the root cause analysis convened in
 * the record's thread instead of a meeting room. */
const NC_RCA_WORLD: ArcadeFlowWorld = {
  team: "Engineering Industries",
  recordNoun: "Non-conformance",
  owner: "J. Rivera",
  ownerInitials: "JR",
  participants: ["JR", "SO", "+3"],
  participantsLabel: "J. Rivera, S. Okafor, and three others",
  recordKicker: "ROOT CAUSE ANALYSIS",
  context: {
    initials: "SO",
    name: "S. Okafor",
    time: "10:41",
    message: "Thickness trend matches the nozzle service log gap.",
    detail: "Maintenance log attached · contributed asynchronously",
  },
  inboxNeighbors: [
    { title: "Incoming inspection", time: "11:02", detail: "Lot 224-A · passed", kind: "Quality event" },
    { title: "Deviation triage", time: "09:15", detail: "Disposition pending", kind: "Quality event" },
    { title: "Supplier corrective action", time: "Yesterday", detail: "SCAR-31 · response received", kind: "Quality event" },
  ],
  checklistTitle: "Root Cause Analysis",
  checklistSections: [
    {
      title: "PARTICIPANTS",
      items: [
        { label: "S. Okafor", note: "Process Engineering · required" },
        { label: "M. Osei", note: "Production · required" },
        { label: "L. Danes", note: "Maintenance · optional" },
      ],
    },
    {
      title: "ANALYSIS · 5-WHY",
      items: [
        { label: "Contributions in thread", note: "Against the attached evidence" },
        { label: "Maintenance log", note: "Nozzle service interval gap" },
        { label: "Sync session", note: "Not needed · analysis held" },
      ],
    },
    {
      title: "ROOT CAUSE STATEMENT",
      items: [
        {
          label: "Agreed cause",
          kind: "field",
          value: "Nozzle wear past service interval · maintenance log confirms",
          note: "Entered on the record",
        },
        { label: "Consensus", kind: "approval", signer: "S. Okafor", state: "3 confirmed" },
        { label: "Analysis trail", note: "Attached · no minutes" },
      ],
    },
  ],
};

/* ============================================================ PF-7 world
 * NC-204 at disposition: the decision, the engineering concession, and the
 * handoff to production, all inside the record. */
const NC_DISPO_WORLD: ArcadeFlowWorld = {
  team: "Engineering Industries",
  recordNoun: "Non-conformance",
  owner: "J. Rivera",
  ownerInitials: "JR",
  participants: ["JR", "DF", "+3"],
  participantsLabel: "J. Rivera, D. Fontaine, and three others",
  recordKicker: "DISPOSITION",
  context: {
    initials: "SO",
    name: "S. Okafor",
    time: "09:26",
    message: "Concession granted for rework to spec.",
    detail: "CON-88 · ruled on the record, not in an email chain",
  },
  inboxNeighbors: [
    { title: "Supplier corrective action", time: "10:12", detail: "SCAR-31 · closing", kind: "Quality event" },
    { title: "Incoming inspection", time: "08:44", detail: "Lot 224-B · sampling due", kind: "Quality event" },
    { title: "Periodic review", time: "Yesterday", detail: "SOP-214 · due Friday", kind: "Review" },
  ],
  checklistTitle: "Disposition",
  checklistSections: [
    {
      title: "DISPOSITION DECISION",
      items: [
        { label: "Options considered", note: "Rework · use-as-is · scrap" },
        {
          label: "Recommendation",
          kind: "field",
          value: "Rework lot 118-B to spec. Nozzle serviced; re-inspect 100% before release.",
          note: "Entered on the record",
        },
        { label: "Justification", note: "Root cause + severity attached" },
      ],
    },
    {
      title: "ENGINEERING CONCESSION",
      items: [
        { label: "Concession request", note: "CON-88 · rework to spec" },
        { label: "Ruling", kind: "approval", signer: "S. Okafor", state: "Granted" },
        { label: "Scope", note: "Lot 118-B rework only" },
      ],
    },
    {
      title: "EXECUTION",
      items: [
        { label: "Production instruction", note: "Record link attached" },
        { label: "Re-inspection", note: "12 of 12 passed" },
        { label: "Completion recorded", note: "Same act as verification" },
      ],
    },
  ],
};

/* ============================================================ PF-3 world
 * CAPA-612, raised from complaint CMP-341: the investigation, the plan, the
 * cross-functional implementation, and the effectiveness verdict read off
 * the live dashboard. */
const CAPA_WORLD: ArcadeFlowWorld = {
  team: "Engineering Industries",
  recordNoun: "CAPA",
  owner: "R. Iyer",
  ownerInitials: "RI",
  participants: ["RI", "DF", "+4"],
  participantsLabel: "R. Iyer, D. Fontaine, and four others",
  recordKicker: "CORRECTIVE ACTION",
  context: {
    initials: "DF",
    name: "D. Fontaine",
    time: "08:31",
    message: "Assigned this CAPA to you from complaint CMP-341.",
    detail: "Recurring seal failure · proposed scope attached",
  },
  inboxNeighbors: [
    { title: "Customer complaint", time: "08:30", detail: "CMP-341 · escalated to CAPA", kind: "Quality event" },
    { title: "Non-conformance", time: "Yesterday", detail: "NC-186 · seal failure · linked", kind: "Quality event" },
    { title: "Management review", time: "Monday", detail: "Q3 quality objectives", kind: "Review" },
  ],
  homeTiles: [
    { label: "My CAPAs", count: 3 },
    { label: "Quality events", count: 6 },
    { label: "My tasks", count: 4 },
  ],
  reports: {
    title: "Quality performance",
    kpis: [
      { label: "Open CAPAs", value: "7", note: "2 due this week" },
      { label: "On-time closure", value: "94%", note: "12-month rolling" },
      { label: "Recurrence", value: "0", note: "since action · 90 days" },
      { label: "Avg. closure", value: "34d", note: "target 45d" },
    ],
    panels: [
      { label: "Recurrence · PRT-4412", kind: "bars" },
      { label: "CAPA aging", kind: "lines" },
      { label: "On-time closure", kind: "donut" },
    ],
  },
  checklistTitle: "Corrective Action",
  checklistSections: [
    {
      title: "INVESTIGATION",
      items: [
        { label: "Originating records", note: "CMP-341 · NC-186 linked" },
        { label: "Root cause analysis", note: "5-Why · interviews attached" },
        {
          label: "Root cause statement",
          kind: "field",
          value: "Seal spec drift at supplier lot level",
          note: "Entered on the CAPA",
        },
      ],
    },
    {
      title: "ACTION PLAN",
      items: [
        { label: "Retrain sealing crew", note: "Training · 30 Sep" },
        { label: "Update SOP-214", note: "R. Mehta · 05 Oct" },
        { label: "Requalify supplier lot", note: "SQE · 12 Oct" },
      ],
    },
    {
      title: "EFFECTIVENESS",
      items: [
        { label: "Review window", note: "90 days after completion" },
        { label: "Recurrence check", note: "0 events · metrics improved" },
        { label: "Part 11 sign-off", kind: "approval", signer: "R. Iyer", state: "Signed", note: "Closes and updates CMP-341" },
      ],
    },
  ],
};

/* ============================================================ PF-11 world
 * SCAR-31: the supplier exchange across the company boundary, run by the
 * Supplier Quality Engineer against Meridian Polymers' seal lot. */
const SCAR_WORLD: ArcadeFlowWorld = {
  team: "Engineering Industries",
  recordNoun: "Supplier NC",
  owner: "H. Blake",
  ownerInitials: "HB",
  participants: ["HB", "TR", "+3"],
  participantsLabel: "H. Blake, T. Ruiz (Meridian), and three others",
  recordKicker: "SUPPLIER QUALITY",
  context: {
    initials: "TR",
    name: "T. Ruiz · Meridian Polymers",
    time: "11:20",
    message: "Investigation report submitted with the lot data attached.",
    detail: "Posted into the record thread · across the company boundary",
  },
  inboxNeighbors: [
    { title: "Incoming inspection", time: "09:05", detail: "Lot 88-D · Meridian · due", kind: "Quality event" },
    { title: "Corrective action", time: "Yesterday", detail: "CAPA-612 · supplier requalification linked", kind: "Quality event" },
    { title: "Supplier scorecard", time: "Monday", detail: "Meridian Polymers · quarterly", kind: "Review" },
  ],
  checklistTitle: "Supplier Quality",
  checklistSections: [
    {
      title: "NOTIFICATION & EVIDENCE",
      items: [
        { label: "Evidence package", note: "Photos · measurements · attached" },
        { label: "Part and containment", note: "Seal lot 88-C · quarantined" },
        { label: "Clarification thread", note: "Captured on the record" },
      ],
    },
    {
      title: "SUPPLIER INVESTIGATION",
      items: [
        { label: "Brief and timeline", note: "8D required · 10 working days" },
        { label: "Investigation report", note: "Submitted into the record" },
        { label: "MRB outcome", note: "Documented on the record" },
      ],
    },
    {
      title: "SCAR & VERIFICATION",
      items: [
        { label: "SCAR requirements", note: "Structured fields · no ambiguity" },
        {
          label: "Corrective action plan",
          kind: "revision",
          from: "Rev A · single-lot check",
          to: "Rev B · 3-lot verification",
          note: "Revised on returned feedback",
        },
        { label: "Next-lot verification", kind: "approval", signer: "H. Blake", state: "Verified", note: "Evidence closes the SCAR" },
      ],
    },
  ],
};

/* ============================================================ PF-2 world
 * AUD-12: the annual ISO 13485 audit the Quality Manager runs from schedule
 * notification to the Part 11 sign-off, tracked on the live dashboard. */
const AUDIT_WORLD: ArcadeFlowWorld = {
  team: "Engineering Industries",
  recordNoun: "Audit",
  owner: "D. Fontaine",
  ownerInitials: "DF",
  participants: ["DF", "LN", "+4"],
  participantsLabel: "D. Fontaine, L. Navarro, and four others",
  recordKicker: "INTERNAL AUDIT",
  context: {
    initials: "LN",
    name: "L. Navarro",
    time: "08:12",
    message: "Checklist drafted from the standard and our procedures.",
    detail: "ISO 13485 full QMS · prior-year findings linked",
  },
  inboxNeighbors: [
    { title: "Corrective action", time: "10:44", detail: "CAPA-612 · effectiveness window", kind: "Quality event" },
    { title: "Management review", time: "Monday", detail: "Q3 quality objectives", kind: "Review" },
    { title: "Periodic review", time: "Yesterday", detail: "SOP-214 · due Friday", kind: "Review" },
  ],
  homeTiles: [
    { label: "My audits", count: 2 },
    { label: "Quality events", count: 6 },
    { label: "Pending approvals", count: 3 },
  ],
  reports: {
    title: "Audit programme",
    kpis: [
      { label: "Findings", value: "7", note: "2 major · 5 minor" },
      { label: "Routed to CA", value: "2", note: "context preserved" },
      { label: "Closed", value: "5", note: "this window" },
      { label: "Overdue", value: "1", note: "escalated" },
    ],
    panels: [
      { label: "Findings by clause", kind: "bars" },
      { label: "Closure aging", kind: "lines" },
      { label: "On-time responses", kind: "donut" },
    ],
  },
  checklistTitle: "Audit",
  checklistSections: [
    {
      title: "SCOPE & PLAN",
      items: [
        { label: "Scope", note: "ISO 13485 · full QMS" },
        { label: "Auditors and stakeholders", note: "Notified with their sections" },
        { label: "Prior-year findings", note: "Linked on the record" },
      ],
    },
    {
      title: "FINDINGS",
      items: [
        {
          label: "Observations",
          kind: "field",
          value: "Coating check skipped on line 2 · photo 12 attached",
          note: "Captured on mobile",
        },
        { label: "Severity and clause", note: "Report writes itself" },
        { label: "Evidence", note: "Attached in real time" },
      ],
    },
    {
      title: "CLOSURE",
      items: [
        { label: "Routed corrective actions", note: "CAPA-618 · audit context" },
        { label: "Responses tracked", note: "Due and overdue notify" },
        { label: "Part 11 sign-off", kind: "approval", signer: "D. Fontaine", state: "Signed", note: "Locks the audit for the year" },
      ],
    },
  ],
};

/* ============================================================ journeys
 * One ArcadeStepConfig per Notion Flow Step, in step order. `source` cites
 * the Product Flow step the scene restages. */
const QMS_FLOW_STEP_SCENES: Record<string, ArcadeStepConfig[]> = {
  /* PF-5 · Quality Engineer captures and contains a non-conformance. */
  "5": [
    {
      source: "PF-5 s1 · capture at detection",
      ghost: "Capture",
      type: "Non-conformance",
      id: "#204",
      title: "Coating thickness out of spec",
      status: "Open",
      actor: "You",
      event: "Created the non-conformance from the line",
      eventDetail: "4 photos and 3 readings attached at the source · live before leaving the line",
      checklist: "CAPTURE & EVIDENCE",
      checklistItems: ["Photos and measurements", "Part and order context", "Problem description"],
      focus: "record",
      focusTitle: "Captured at the point of detection",
      focusRows: ["Captured on mobile · Line 2", "Evidence attached at the source"],
      focusAction: "Open live record",
      ownershipNote: "Point of detection · in-process check",
      world: NC_CAPTURE_WORLD,
      checklistOpen: "CAPTURE & EVIDENCE",
      checklistProgress: { "CAPTURE & EVIDENCE": 1, CONTAINMENT: 0, "SEVERITY & HISTORY": 0 },
    },
    {
      source: "PF-5 s2 · triage from notification",
      ghost: "Triage",
      type: "Non-conformance",
      id: "#204",
      title: "Coating thickness out of spec",
      status: "Open",
      actor: "automator",
      event: "Notified the supervisor and quality engineer",
      eventDetail: "Photos, measurements, and context attached · triage from the record",
      checklist: "CAPTURE & EVIDENCE",
      checklistItems: ["Photos and measurements", "Part and order context"],
      focus: "queue",
      focusTitle: "Non-conformances",
      focusRows: ["NC-204 · Coating thickness · Line 2", "Evidence attached · no floor visit needed", "Triage from the record alone"],
      focusAction: "Open record",
      ownershipNote: "Many cases resolve from the record alone",
      world: NC_CAPTURE_WORLD,
      queueTile: "Non-conformances",
      checklistProgress: { "CAPTURE & EVIDENCE": 1, CONTAINMENT: 0, "SEVERITY & HISTORY": 0 },
    },
    {
      source: "PF-5 s3 · ERP context confirmed",
      ghost: "Context",
      type: "Non-conformance",
      id: "#204",
      title: "Coating thickness out of spec",
      status: "Open",
      actor: "automator",
      event: "Attached part and order context from the ERP",
      eventDetail: "Nothing re-keyed · review and confirm instead of looking values up",
      checklist: "CAPTURE & EVIDENCE",
      checklistItems: ["Part PRT-4412 · confirmed", "Work order WO-8817 · linked", "BOM revision C · matched"],
      focus: "trace",
      focusTitle: "Context pulled from the ERP",
      focusRows: ["Confirmed by J. Rivera", "Confirm context"],
      focusAction: "Confirm context",
      ownershipNote: "Right part, order, and revision",
      world: NC_CAPTURE_WORLD,
      checklistOpen: "CAPTURE & EVIDENCE",
      checklistProgress: { "CAPTURE & EVIDENCE": 2, CONTAINMENT: 0, "SEVERITY & HISTORY": 0 },
    },
    {
      source: "PF-5 s4 · problem description",
      ghost: "Describe",
      type: "Non-conformance",
      id: "#204",
      title: "Coating thickness out of spec",
      status: "Open",
      actor: "You",
      event: "Writing the problem description on the checklist",
      eventDetail: "Entered against the photos and readings instead of reconstructing them",
      checklist: "CAPTURE & EVIDENCE",
      checklistItems: ["Problem description", "Evidence referenced"],
      focus: "checklist",
      focusTitle: "Data entry, on the record",
      focusRows: ["Evidence · 4 photos · 3 readings"],
      focusAction: "Save description",
      ownershipNote: "Written for investigators who were not on the floor",
      world: NC_CAPTURE_WORLD,
      checklistOpen: "CAPTURE & EVIDENCE",
      checklistEntry: { section: "CAPTURE & EVIDENCE", item: "Problem description" },
      checklistProgress: { "CAPTURE & EVIDENCE": 2, CONTAINMENT: 0, "SEVERITY & HISTORY": 0 },
    },
    {
      source: "PF-5 s5 · containment tasked",
      ghost: "Contain",
      type: "Non-conformance",
      id: "#204",
      title: "Coating thickness out of spec",
      status: "Containment",
      actor: "You",
      event: "Recorded containment and assigned it as tasks",
      eventDetail: "Production owners notified with record context · nobody chased by phone",
      checklist: "CONTAINMENT",
      checklistItems: ["Quarantine lot 118-B", "Sort remaining WIP", "Hold shipment"],
      focus: "tasks",
      focusTitle: "Containment actions",
      focusRows: ["Quarantine lot 118-B · M. Osei", "Sort remaining WIP · Line 2", "Hold shipment · Logistics"],
      focusAction: "Assign containment tasks",
      ownershipNote: "Severity decides the actions · each has an owner",
      world: NC_CAPTURE_WORLD,
      checklistOpen: "CONTAINMENT",
      checklistProgress: { "CAPTURE & EVIDENCE": 3, CONTAINMENT: 1, "SEVERITY & HISTORY": 0 },
    },
    {
      source: "PF-5 s6 · severity with linked history",
      ghost: "Assess",
      type: "Non-conformance",
      id: "#204",
      title: "Coating thickness out of spec",
      status: "Assessment",
      actor: "automator",
      event: "Surfaced prior events for the same part and process",
      eventDetail: "History in view on the record, not dug out of spreadsheets",
      checklist: "SEVERITY & HISTORY",
      checklistItems: ["Severity", "Prior events"],
      focus: "history",
      focusKicker: "PRIOR EVENTS · PRT-4412",
      focusTitle: "Recurrence in view",
      focusRows: ["NC-204 · Coating thickness · today", "NC-171 · Coating thickness · May 2026", "NC-98 · Adhesion · Jan 2026"],
      focusAction: "Assess severity",
      ownershipNote: "Isolated event or systemic issue · judged with history",
      world: NC_CAPTURE_WORLD,
      checklistOpen: "SEVERITY & HISTORY",
      checklistProgress: { "CAPTURE & EVIDENCE": 3, CONTAINMENT: 2, "SEVERITY & HISTORY": 1 },
    },
    {
      source: "PF-5 s7 · formal problem statement",
      ghost: "State",
      type: "Non-conformance",
      id: "#204",
      title: "Coating thickness out of spec",
      status: "Assessment",
      actor: "You",
      event: "Defined the formal problem statement",
      eventDetail: "Anchored to the evidence, context, and severity already in place",
      checklist: "SEVERITY & HISTORY",
      checklistItems: ["Problem statement"],
      focus: "record",
      poseVariant: "statement",
      focusTitle: "The problem, scoped",
      focusRows: ["Severity Major · recurrence suspected", "Statement precise enough to scope the investigation"],
      focusAction: "Save problem statement",
      ownershipNote: "Second occurrence on PRT-4412 in 12 months",
      world: NC_CAPTURE_WORLD,
      checklistOpen: "SEVERITY & HISTORY",
      checklistProgress: { "CAPTURE & EVIDENCE": 3, CONTAINMENT: 2, "SEVERITY & HISTORY": 2 },
    },
    {
      source: "PF-5 s8 · investigation team pulled in",
      ghost: "Convene",
      type: "Non-conformance",
      id: "#204",
      title: "Coating thickness out of spec",
      status: "Investigation",
      actor: "You",
      event: "Pulled the investigation team onto the record",
      eventDetail: "Each notification carries the record link, statement, and evidence · nobody arrives needing a briefing",
      checklist: "SEVERITY & HISTORY",
      checklistItems: ["Investigation team"],
      focus: "queue",
      poseVariant: "route",
      focusKicker: "INVESTIGATION TEAM",
      focusTitle: "Structured notification",
      focusRows: ["S. Okafor · Process Engineering", "M. Osei · Production · Line 2", "D. Fontaine · Quality Manager"],
      focusAction: "Notify with record context",
      ownershipNote: "Who the investigation needs, on the record",
      world: NC_CAPTURE_WORLD,
      checklistProgress: { "CAPTURE & EVIDENCE": 3, CONTAINMENT: 3, "SEVERITY & HISTORY": 2 },
      related: 2,
    },
  ],

  /* PF-6 · Quality Engineer drives root cause analysis in the record thread. */
  "6": [
    {
      source: "PF-6 s1 · participants pulled in",
      ghost: "Convene",
      type: "Non-conformance",
      id: "#204",
      title: "Coating thickness out of spec",
      status: "Investigation",
      actor: "You",
      event: "Pulled cross-functional participants into the thread",
      eventDetail: "No calendar negotiation, no meeting invite · full record context in each notification",
      checklist: "PARTICIPANTS",
      checklistItems: ["S. Okafor", "M. Osei", "L. Danes"],
      focus: "queue",
      poseVariant: "route",
      focusKicker: "THREAD PARTICIPANTS",
      focusTitle: "The analysis convenes here",
      focusRows: ["S. Okafor · Process Engineering · required", "M. Osei · Production · required", "L. Danes · Maintenance · optional"],
      focusAction: "Add to record thread",
      ownershipNote: "Contribute when they can, in context",
      world: NC_RCA_WORLD,
      checklistProgress: { PARTICIPANTS: 2, "ANALYSIS · 5-WHY": 0, "ROOT CAUSE STATEMENT": 0 },
    },
    {
      source: "PF-6 s2 · context reviewed asynchronously",
      ghost: "Review",
      type: "Non-conformance",
      id: "#204",
      title: "Coating thickness out of spec",
      status: "Investigation",
      actor: "Unifize Assistant",
      event: "Assembled the evidence, history, and problem statement",
      eventDetail: "Reviewed asynchronously · nobody rebuilds context from printed packets",
      checklist: "PARTICIPANTS",
      checklistItems: ["Evidence", "History", "Problem statement"],
      focus: "record",
      focusTitle: "The assembled context",
      focusRows: ["Evidence, history, statement · one record", "Complete enough to start the analysis"],
      focusAction: "Start the analysis",
      ownershipNote: "Each participant reads in their own time",
      world: NC_RCA_WORLD,
      checklistOpen: "PARTICIPANTS",
      checklistProgress: { PARTICIPANTS: 3, "ANALYSIS · 5-WHY": 0, "ROOT CAUSE STATEMENT": 0 },
    },
    {
      source: "PF-6 s3 · structured 5-Why in thread",
      ghost: "Analyse",
      type: "Non-conformance",
      id: "#204",
      title: "Coating thickness out of spec",
      status: "Investigation",
      actor: "You",
      event: "Ran the 5-Why in the record thread",
      eventDetail: "Contributions land against the evidence · a sync session only if the analysis stalls",
      checklist: "ANALYSIS · 5-WHY",
      checklistItems: ["Contributions in thread", "Maintenance log"],
      focus: "comment",
      focusTitle: "Analysis against evidence",
      focusRows: ["5-Why analysis · anchored to the maintenance log"],
      focusAction: "Contribute in thread",
      ownershipNote: "When to stop digging is the analyst's call",
      world: NC_RCA_WORLD,
      checklistOpen: "ANALYSIS · 5-WHY",
      checklistProgress: { PARTICIPANTS: 3, "ANALYSIS · 5-WHY": 2, "ROOT CAUSE STATEMENT": 0 },
    },
    {
      source: "PF-6 s4 · root cause agreed",
      ghost: "Agree",
      type: "Non-conformance",
      id: "#204",
      title: "Coating thickness out of spec",
      status: "In Review",
      actor: "You",
      event: "Put the root cause to the participants",
      eventDetail: "Confirm or challenge in the thread, against the evidence · disputes resolve in context",
      checklist: "ANALYSIS · 5-WHY",
      checklistItems: ["Consensus"],
      focus: "review",
      focusTitle: "Root cause consensus",
      focusRows: [
        "Proposed cause · Nozzle wear past service interval",
        "Evidence · thickness trend + maintenance log",
        "Participants · 3 confirmed in thread",
      ],
      focusAction: "Confirm root cause",
      focusAlts: ["Challenge in thread"],
      ownershipNote: "No second scheduled meeting",
      world: NC_RCA_WORLD,
      checklistOpen: "ANALYSIS · 5-WHY",
      checklistProgress: { PARTICIPANTS: 3, "ANALYSIS · 5-WHY": 3, "ROOT CAUSE STATEMENT": 0 },
    },
    {
      source: "PF-6 s5 · statement carries its justification",
      ghost: "Record",
      type: "Non-conformance",
      id: "#204",
      title: "Coating thickness out of spec",
      status: "Cause Agreed",
      actor: "You",
      event: "Documented the agreed root cause statement",
      eventDetail: "The analysis trail stays attached · no minutes to write or distribute",
      checklist: "ROOT CAUSE STATEMENT",
      checklistItems: ["Agreed cause", "Analysis trail"],
      focus: "diff",
      focusKicker: "ROOT CAUSE STATEMENT",
      focusTitle: "The agreed statement",
      focusRows: [
        "First guess · operator error, unsupported",
        "Agreed · nozzle wear past service interval, log confirms",
        "Specific enough to drive corrective action definition",
      ],
      focusAction: "Root cause recorded",
      ownershipNote: "The statement carries its own justification",
      world: NC_RCA_WORLD,
      checklistOpen: "ROOT CAUSE STATEMENT",
      checklistProgress: { PARTICIPANTS: 3, "ANALYSIS · 5-WHY": 3, "ROOT CAUSE STATEMENT": 3 },
    },
  ],

  /* PF-7 · Quality Engineer dispositions and routes for approval. */
  "7": [
    {
      source: "PF-7 s1 · options from root cause and severity",
      ghost: "Decide",
      type: "Non-conformance",
      id: "#204",
      title: "Coating thickness out of spec",
      status: "Disposition",
      actor: "You",
      event: "Reviewed root cause and severity to frame the options",
      eventDetail: "Rework, use-as-is, scrap, return to supplier · judged on the record",
      checklist: "DISPOSITION DECISION",
      checklistItems: ["Options considered"],
      focus: "review",
      focusTitle: "Disposition options",
      focusRows: [
        "Rework · viable, concession needed",
        "Use-as-is · out of spec, rejected",
        "Scrap · fallback if rework fails",
      ],
      focusAction: "Evaluate options",
      focusAlts: ["Return to supplier"],
      ownershipNote: "Root cause and severity in view",
      world: NC_DISPO_WORLD,
      checklistOpen: "DISPOSITION DECISION",
      checklistProgress: { "DISPOSITION DECISION": 1, "ENGINEERING CONCESSION": 0, EXECUTION: 0 },
    },
    {
      source: "PF-7 s2 · concession inside the record",
      ghost: "Route",
      type: "Non-conformance",
      id: "#204",
      title: "Coating thickness out of spec",
      status: "Disposition",
      actor: "You",
      event: "Routed a concession request to engineering",
      eventDetail: "Engineering reviews with full evidence in context · answers on the record, not an email chain",
      checklist: "ENGINEERING CONCESSION",
      checklistItems: ["Concession request", "Ruling"],
      focus: "comment",
      focusTitle: "The concession request",
      focusRows: ["Concession CON-88 · rework to spec · S. Okafor"],
      focusAction: "Request concession",
      ownershipNote: "What engineering needs to rule on, stated",
      world: NC_DISPO_WORLD,
      checklistOpen: "ENGINEERING CONCESSION",
      checklistProgress: { "DISPOSITION DECISION": 1, "ENGINEERING CONCESSION": 1, EXECUTION: 0 },
    },
    {
      source: "PF-7 s3 · recommendation with justification attached",
      ghost: "Prepare",
      type: "Non-conformance",
      id: "#204",
      title: "Coating thickness out of spec",
      status: "Disposition",
      actor: "You",
      event: "Prepared the disposition recommendation",
      eventDetail: "Root cause, severity, and concession already attached as its justification",
      checklist: "DISPOSITION DECISION",
      checklistItems: ["Recommendation", "Justification"],
      focus: "record",
      poseVariant: "statement",
      focusTitle: "Rework to spec",
      focusRows: ["Recommendation · rework lot 118-B to spec", "Justification attached · nothing reconstructed"],
      focusAction: "Prepare for approval",
      ownershipNote: "Concession CON-88 granted",
      world: NC_DISPO_WORLD,
      checklistOpen: "DISPOSITION DECISION",
      checklistProgress: { "DISPOSITION DECISION": 3, "ENGINEERING CONCESSION": 2, EXECUTION: 0 },
    },
    {
      source: "PF-7 s4 · submitted for approval",
      ghost: "Submit",
      type: "Non-conformance",
      id: "#204",
      title: "Coating thickness out of spec",
      status: "Needs Approval",
      actor: "You",
      event: "Submitted the disposition for approval",
      eventDetail: "The record shows where the approval stands · no status-chasing",
      checklist: "ENGINEERING CONCESSION",
      checklistItems: ["Approval route"],
      focus: "queue",
      poseVariant: "route",
      focusTitle: "One notification, whole package",
      focusRows: [
        "D. Fontaine · Quality Manager · required",
        "Recommendation + evidence · one place",
        "Concession CON-88 · attached",
      ],
      focusAction: "Submit for approval",
      ownershipNote: "Complete enough for first-time approval",
      world: NC_DISPO_WORLD,
      checklistProgress: { "DISPOSITION DECISION": 3, "ENGINEERING CONCESSION": 3, EXECUTION: 0 },
    },
    {
      source: "PF-7 s5 · approval flows to production",
      ghost: "Handoff",
      type: "Non-conformance",
      id: "#204",
      title: "Coating thickness out of spec",
      status: "Approved",
      actor: "automator",
      event: "Routed the disposition instruction to production",
      eventDetail: "Record link attached · the handoff confirms itself, no relay by email and phone",
      checklist: "EXECUTION",
      checklistItems: ["Production instruction"],
      focus: "record",
      poseVariant: "handoff",
      focusTitle: "Approved and moving",
      focusRows: ["Instruction · rework lot 118-B to spec", "Line 2 notified with the record attached"],
      focusAction: "Watch the handoff confirm",
      ownershipNote: "Intervene only if production queries it",
      world: NC_DISPO_WORLD,
      signedItems: [
        { name: "D. Fontaine", initials: "DF", role: "Quality Manager", approvalId: "NC-204-D1", time: "14:05" },
      ],
      checklistOpen: "EXECUTION",
      checklistProgress: { "DISPOSITION DECISION": 3, "ENGINEERING CONCESSION": 3, EXECUTION: 1 },
    },
    {
      source: "PF-7 s6 · execution verified, completion recorded",
      ghost: "Verify",
      type: "Non-conformance",
      id: "#204",
      title: "Coating thickness out of spec",
      status: "Completed",
      actor: "You",
      event: "Verified execution and recorded completion",
      eventDetail: "Evidence attached by production · verification and completion in the same act",
      checklist: "EXECUTION",
      checklistItems: ["Rework completed · Line 2", "Re-inspection passed · 12 of 12", "Completion recorded on NC-204"],
      focus: "trace",
      focusTitle: "Disposition executed",
      focusRows: ["Evidence attached by production", "Close containment"],
      focusAction: "Record completion",
      ownershipNote: "Executed as approved",
      world: NC_DISPO_WORLD,
      checklistOpen: "EXECUTION",
      checklistProgress: { "DISPOSITION DECISION": 3, "ENGINEERING CONCESSION": 3, EXECUTION: 3 },
      related: 2,
    },
  ],

  /* PF-3 · CAPA Investigator closes a corrective action from a complaint. */
  "3": [
    {
      source: "PF-3 s1 · assignment notification",
      ghost: "Assign",
      type: "CAPA",
      id: "#612",
      title: "Recurring seal failure",
      status: "Assigned",
      actor: "automator",
      event: "Assigned this CAPA with scope attached",
      eventDetail: "Originating complaint CMP-341 and proposed scope in the notification itself",
      checklist: "INVESTIGATION",
      checklistItems: ["Originating records"],
      focus: "queue",
      focusTitle: "My CAPAs",
      focusRows: [
        "CAPA-612 · Recurring seal failure · assigned to you",
        "Scope · complaint CMP-341 · seal supplier lots",
        "Decide before opening the record",
      ],
      focusAction: "Accept assignment",
      ownershipNote: "Accept, or request reassignment on scope",
      world: CAPA_WORLD,
      queueTile: "My CAPAs",
      checklistProgress: { INVESTIGATION: 0, "ACTION PLAN": 0, EFFECTIVENESS: 0 },
    },
    {
      source: "PF-3 s2 · originating records in one view",
      ghost: "Open",
      type: "CAPA",
      id: "#612",
      title: "Recurring seal failure",
      status: "Investigation",
      actor: "You",
      event: "Opened the CAPA and reviewed the originating records",
      eventDetail: "Complaint, non-conformance, evidence, and prior events · no bouncing across systems",
      checklist: "INVESTIGATION",
      checklistItems: ["Originating records", "Prior related events"],
      focus: "record",
      focusTitle: "Full context, one record",
      focusRows: ["Linked · CMP-341 + NC-186", "Evidence and history in the same view"],
      focusAction: "Accept scope",
      ownershipNote: "Push back to the originator before starting, if needed",
      world: CAPA_WORLD,
      checklistOpen: "INVESTIGATION",
      checklistProgress: { INVESTIGATION: 1, "ACTION PLAN": 0, EFFECTIVENESS: 0 },
    },
    {
      source: "PF-3 s3 · root cause on the CAPA",
      ghost: "Analyse",
      type: "CAPA",
      id: "#612",
      title: "Recurring seal failure",
      status: "Investigation",
      actor: "You",
      event: "Recorded findings from the root cause analysis",
      eventDetail: "5-Whys with interviews by voice and comment · findings land on the CAPA directly",
      checklist: "INVESTIGATION",
      checklistItems: ["Root cause analysis", "Interview notes"],
      focus: "comment",
      focusTitle: "Findings on the record",
      focusRows: ["5-Why · interview notes attached"],
      focusAction: "Record finding",
      ownershipNote: "When to stop digging is the analyst's call",
      world: CAPA_WORLD,
      checklistOpen: "INVESTIGATION",
      checklistProgress: { INVESTIGATION: 2, "ACTION PLAN": 0, EFFECTIVENESS: 0 },
    },
    {
      source: "PF-3 s4 · the plan, each step owned",
      ghost: "Plan",
      type: "CAPA",
      id: "#612",
      title: "Recurring seal failure",
      status: "Planning",
      actor: "You",
      event: "Drafted the corrective action plan",
      eventDetail: "Containment, corrective, preventive · each step has an owner, a date, and a definition of done",
      checklist: "ACTION PLAN",
      checklistItems: ["Retrain sealing crew", "Update SOP-214", "Requalify supplier lot"],
      focus: "tasks",
      poseVariant: "plan",
      focusTitle: "The action plan",
      focusRows: ["Retrain sealing crew · Training", "Update SOP-214 · R. Mehta", "Requalify supplier lot · SQE"],
      focusAction: "Define the plan",
      ownershipNote: "Include, defer, or drop · the planner's call",
      world: CAPA_WORLD,
      checklistOpen: "ACTION PLAN",
      checklistProgress: { INVESTIGATION: 3, "ACTION PLAN": 0, EFFECTIVENESS: 0 },
      checklistFootnote: "Every action owned and dated",
    },
    {
      source: "PF-3 s5 · plan routed for approval",
      ghost: "Route",
      type: "CAPA",
      id: "#612",
      title: "Recurring seal failure",
      status: "Needs Approval",
      actor: "You",
      event: "Routed the plan to the Quality Manager",
      eventDetail: "One notification · approve, reject, or request changes directly on the record",
      checklist: "ACTION PLAN",
      checklistItems: ["Approval route"],
      focus: "queue",
      poseVariant: "route",
      focusTitle: "Approval by risk level",
      focusRows: [
        "D. Fontaine · Quality Manager · required",
        "Risk level · Major · single approver",
        "Plan + evidence · one package",
      ],
      focusAction: "Route for approval",
      ownershipNote: "Who approves is set by the risk level",
      world: CAPA_WORLD,
      checklistProgress: { INVESTIGATION: 3, "ACTION PLAN": 1, EFFECTIVENESS: 0 },
    },
    {
      source: "PF-3 s6 · implementation with evidence capture",
      ghost: "Implement",
      type: "CAPA",
      id: "#612",
      title: "Recurring seal failure",
      status: "Implementation",
      actor: "You",
      event: "Coordinated action owners and captured evidence",
      eventDetail: "Cross-functional, across sites · training records, updated SOPs, requalification, as each completes",
      checklist: "ACTION PLAN",
      checklistItems: ["Retrain sealing crew", "Update SOP-214", "Requalify supplier lot"],
      focus: "tasks",
      focusTitle: "Actions with evidence",
      focusRows: ["Retrain sealing crew · Training", "Update SOP-214 · R. Mehta", "Requalify supplier lot · SQE"],
      focusAction: "Capture evidence",
      ownershipNote: "Sufficient evidence is the coordinator's call",
      world: CAPA_WORLD,
      checklistOpen: "ACTION PLAN",
      checklistProgress: { INVESTIGATION: 3, "ACTION PLAN": 2, EFFECTIVENESS: 0 },
    },
    {
      source: "PF-3 s7 · effectiveness review scheduled",
      ghost: "Schedule",
      type: "CAPA",
      id: "#612",
      title: "Recurring seal failure",
      status: "Monitoring",
      actor: "automator",
      event: "Scheduled the effectiveness review",
      eventDetail: "An obligation lands on the Investigator's queue at the review date · nothing rests on memory",
      checklist: "EFFECTIVENESS",
      checklistItems: ["Review window"],
      focus: "queue",
      focusTitle: "My tasks",
      focusRows: [
        "Effectiveness review · CAPA-612 · due 30 Oct",
        "Obligation added to your queue",
        "Notification scheduled at the window",
      ],
      focusAction: "Set window · 90 days",
      ownershipNote: "30 to 90 days after action completion",
      world: CAPA_WORLD,
      queueTile: "My tasks",
      checklistOpen: "EFFECTIVENESS",
      checklistProgress: { INVESTIGATION: 3, "ACTION PLAN": 3, EFFECTIVENESS: 1 },
    },
    {
      source: "PF-3 s8 · effectiveness read off the dashboard",
      ghost: "Close",
      type: "CAPA",
      id: "#612",
      title: "Recurring seal failure",
      status: "Effective",
      actor: "You",
      event: "Verified effectiveness against the live metrics",
      eventDetail: "No recurrence in the window, metrics improved · sign-off closes the CAPA and updates CMP-341",
      checklist: "EFFECTIVENESS",
      checklistItems: ["Recurrence check", "Part 11 sign-off"],
      focus: "dashboard",
      focusTitle: "Recurrence · PRT-4412",
      focusRows: [
        "0 events since action · 90-day window",
        "Line 2 seal trend · improving",
        "Complaint CMP-341 · updated on close",
      ],
      focusAction: "Sign off effectiveness",
      ownershipNote: "Effective, partially effective, or reopen",
      world: CAPA_WORLD,
      checklistProgress: { INVESTIGATION: 3, "ACTION PLAN": 3, EFFECTIVENESS: 3 },
    },
  ],

  /* PF-11 · SQE drives supplier notification, investigation, and SCAR. */
  "11": [
    {
      source: "PF-11 s1 · one structured notification",
      ghost: "Notify",
      type: "Supplier NC",
      id: "#31",
      title: "Seal lot out of spec · Meridian",
      status: "Notified",
      actor: "You",
      event: "Sent the supplier notification from the record",
      eventDetail: "Evidence package, part context, and containment attach automatically · no email chain with missing attachments",
      checklist: "NOTIFICATION & EVIDENCE",
      checklistItems: ["Evidence package", "Part and containment"],
      focus: "comment",
      focusTitle: "The whole package, once",
      focusRows: ["Evidence package · photos + containment status"],
      focusAction: "Send to supplier",
      ownershipNote: "Complete enough to send is the sender's call",
      world: SCAR_WORLD,
      checklistOpen: "NOTIFICATION & EVIDENCE",
      checklistProgress: { "NOTIFICATION & EVIDENCE": 2, "SUPPLIER INVESTIGATION": 0, "SCAR & VERIFICATION": 0 },
    },
    {
      source: "PF-11 s2 · clarification in the thread",
      ghost: "Clarify",
      type: "Supplier NC",
      id: "#31",
      title: "Seal lot out of spec · Meridian",
      status: "Notified",
      actor: "Unifize Assistant",
      event: "Captured the supplier's questions against the record",
      eventDetail: "The full exchange lives in the thread, not scattered across inboxes",
      checklist: "NOTIFICATION & EVIDENCE",
      checklistItems: ["Clarification thread"],
      focus: "record",
      focusTitle: "The exchange, on the record",
      focusRows: ["Clarification thread · 4 messages", "Scope unchanged · no re-investigation"],
      focusAction: "Reply in thread",
      ownershipNote: "Scope change would reopen the investigation",
      world: SCAR_WORLD,
      checklistOpen: "NOTIFICATION & EVIDENCE",
      checklistProgress: { "NOTIFICATION & EVIDENCE": 3, "SUPPLIER INVESTIGATION": 0, "SCAR & VERIFICATION": 0 },
    },
    {
      source: "PF-11 s3 · the brief, not a phone call",
      ghost: "Brief",
      type: "Supplier NC",
      id: "#31",
      title: "Seal lot out of spec · Meridian",
      status: "Investigation",
      actor: "You",
      event: "Set the investigation brief and timeline",
      eventDetail: "Scope, deliverables, and deadlines on the record · nothing verbal goes unrecorded",
      checklist: "SUPPLIER INVESTIGATION",
      checklistItems: ["Brief and timeline"],
      focus: "tasks",
      poseVariant: "plan",
      focusTitle: "The structured brief",
      focusRows: ["8D methodology · required", "Root cause + data · deliverables", "10 working days · deadline"],
      focusAction: "Issue the brief",
      ownershipNote: "Methodology and time are the SQE's call",
      world: SCAR_WORLD,
      checklistOpen: "SUPPLIER INVESTIGATION",
      checklistProgress: { "NOTIFICATION & EVIDENCE": 3, "SUPPLIER INVESTIGATION": 1, "SCAR & VERIFICATION": 0 },
      checklistFootnote: "The supplier sees deadlines, not hearsay",
    },
    {
      source: "PF-11 s4 · adequacy against the brief",
      ghost: "Evaluate",
      type: "Supplier NC",
      id: "#31",
      title: "Seal lot out of spec · Meridian",
      status: "In Review",
      actor: "You",
      event: "Evaluated the supplier's investigation report",
      eventDetail: "Root cause, data, and proposed actions reviewed against the original brief",
      checklist: "SUPPLIER INVESTIGATION",
      checklistItems: ["Investigation report"],
      focus: "review",
      focusTitle: "Investigation adequacy",
      focusRows: [
        "Root cause analysis · plausible, data-backed",
        "Supporting data · lot records attached",
        "Proposed actions · partially scoped",
      ],
      focusAction: "Assess against brief",
      focusAlts: ["Flag gaps"],
      ownershipNote: "Adequate, or gaps before proceeding",
      world: SCAR_WORLD,
      checklistOpen: "SUPPLIER INVESTIGATION",
      checklistProgress: { "NOTIFICATION & EVIDENCE": 3, "SUPPLIER INVESTIGATION": 2, "SCAR & VERIFICATION": 0 },
    },
    {
      source: "PF-11 s5 · gaps, with the report attached",
      ghost: "Probe",
      type: "Supplier NC",
      id: "#31",
      title: "Seal lot out of spec · Meridian",
      status: "In Review",
      actor: "You",
      event: "Posted the specific gaps back to the supplier",
      eventDetail: "The original report stays attached, so what was insufficient is exact",
      checklist: "SUPPLIER INVESTIGATION",
      checklistItems: ["Gap request"],
      focus: "comment",
      focusTitle: "Precise, not a phone call",
      focusRows: ["Gap request · deeper cause on mixing step · report attached"],
      focusAction: "Request detail",
      ownershipNote: "Which gaps to flag is the assessor's call",
      world: SCAR_WORLD,
      checklistOpen: "SUPPLIER INVESTIGATION",
      checklistProgress: { "NOTIFICATION & EVIDENCE": 3, "SUPPLIER INVESTIGATION": 2, "SCAR & VERIFICATION": 0 },
    },
    {
      source: "PF-11 s6 · MRB documented on the record",
      ghost: "Review",
      type: "Supplier NC",
      id: "#31",
      title: "Seal lot out of spec · Meridian",
      status: "In Review",
      actor: "You",
      event: "Convened the Material Review Board",
      eventDetail: "Decisions, action items, and scope changes land on the record after the meeting",
      checklist: "SUPPLIER INVESTIGATION",
      checklistItems: ["MRB outcome"],
      focus: "queue",
      poseVariant: "route",
      focusKicker: "MATERIAL REVIEW BOARD",
      focusTitle: "Cross-functional review",
      focusRows: [
        "D. Fontaine · Quality Manager",
        "S. Okafor · Process Engineering",
        "H. Blake · Supplier Quality",
      ],
      focusAction: "Document outcomes",
      ownershipNote: "The investigation history stays complete",
      world: SCAR_WORLD,
      checklistProgress: { "NOTIFICATION & EVIDENCE": 3, "SUPPLIER INVESTIGATION": 3, "SCAR & VERIFICATION": 0 },
    },
    {
      source: "PF-11 s7 · the decision trail travels",
      ghost: "Share",
      type: "Supplier NC",
      id: "#31",
      title: "Seal lot out of spec · Meridian",
      status: "In Review",
      actor: "automator",
      event: "Communicated the outcome to the supplier",
      eventDetail: "The supplier sees the decision trail, not just the conclusion",
      checklist: "SUPPLIER INVESTIGATION",
      checklistItems: ["Outcome shared"],
      focus: "record",
      poseVariant: "outcome",
      focusTitle: "Outcome, with its reasoning",
      focusRows: ["Investigation outcome · shared through the record", "Next steps · corrective action to follow"],
      focusAction: "Send outcome",
      ownershipNote: "How much internal detail to share is judged here",
      world: SCAR_WORLD,
      checklistOpen: "SUPPLIER INVESTIGATION",
      checklistProgress: { "NOTIFICATION & EVIDENCE": 3, "SUPPLIER INVESTIGATION": 3, "SCAR & VERIFICATION": 0 },
    },
    {
      source: "PF-11 s8 · is a SCAR warranted",
      ghost: "Decide",
      type: "Supplier NC",
      id: "#31",
      title: "Seal lot out of spec · Meridian",
      status: "In Review",
      actor: "You",
      event: "Weighed severity and history for a formal SCAR",
      eventDetail: "Requirements, evidence of effectiveness, and timeline defined on the record",
      checklist: "SCAR & VERIFICATION",
      checklistItems: ["SCAR decision"],
      focus: "review",
      focusTitle: "SCAR warranted?",
      focusRows: [
        "Severity · Major · customer-facing",
        "History · second event this year",
        "Recurrence risk · justifies formal SCAR",
      ],
      focusAction: "Issue SCAR",
      focusAlts: ["Close without SCAR"],
      ownershipNote: "Scope of corrective action set here",
      world: SCAR_WORLD,
      checklistOpen: "SCAR & VERIFICATION",
      checklistProgress: { "NOTIFICATION & EVIDENCE": 3, "SUPPLIER INVESTIGATION": 3, "SCAR & VERIFICATION": 1 },
    },
    {
      source: "PF-11 s9 · structured fields, no ambiguity",
      ghost: "Send",
      type: "Supplier NC",
      id: "#31",
      title: "Seal lot out of spec · Meridian",
      status: "SCAR Issued",
      actor: "You",
      event: "Sent the SCAR with structured requirements",
      eventDetail: "Requirements, evidence expectations, and timeline as fields, not free-text paragraphs",
      checklist: "SCAR & VERIFICATION",
      checklistItems: ["SCAR requirements"],
      focus: "tasks",
      focusTitle: "The SCAR requirements",
      focusRows: [
        "Corrective action · mixing step control",
        "Evidence of effectiveness · 3 lots data",
        "Verification timeline · 60 days",
      ],
      focusAction: "Send SCAR",
      ownershipNote: "Held only for internal alignment",
      world: SCAR_WORLD,
      checklistOpen: "SCAR & VERIFICATION",
      checklistProgress: { "NOTIFICATION & EVIDENCE": 3, "SUPPLIER INVESTIGATION": 3, "SCAR & VERIFICATION": 1 },
    },
    {
      source: "PF-11 s10 · plan against requirements",
      ghost: "Assess",
      type: "Supplier NC",
      id: "#31",
      title: "Seal lot out of spec · Meridian",
      status: "In Review",
      actor: "You",
      event: "Assessed the supplier's corrective action plan",
      eventDetail: "Reviewed against the SCAR requirements · does it address the root cause",
      checklist: "SCAR & VERIFICATION",
      checklistItems: ["Corrective action plan"],
      focus: "review",
      focusTitle: "Plan adequacy",
      focusRows: [
        "Root cause addressed · partially",
        "Evidence plan · weak on verification",
        "Timeline · acceptable",
      ],
      focusAction: "Needs revision",
      focusAlts: ["Accept plan"],
      ownershipNote: "Credible effectiveness evidence is the bar",
      world: SCAR_WORLD,
      checklistOpen: "SCAR & VERIFICATION",
      checklistProgress: { "NOTIFICATION & EVIDENCE": 3, "SUPPLIER INVESTIGATION": 3, "SCAR & VERIFICATION": 2 },
    },
    {
      source: "PF-11 s11 · rejection the supplier can act on",
      ghost: "Return",
      type: "Supplier NC",
      id: "#31",
      title: "Seal lot out of spec · Meridian",
      status: "In Review",
      actor: "You",
      event: "Returned the plan with structured feedback",
      eventDetail: "The rejection rationale is on the record · the supplier knows exactly what to fix",
      checklist: "SCAR & VERIFICATION",
      checklistItems: ["Plan revision"],
      focus: "diff",
      focusKicker: "PLAN REVISION",
      focusTitle: "What to fix, exactly",
      focusRows: [
        "Verification · single-lot visual check",
        "Verification · 3 lots, dimensional + records",
        "Timeline extended 2 weeks with rationale",
      ],
      focusAction: "Return for revision",
      ownershipNote: "Deficiencies flagged one by one",
      world: SCAR_WORLD,
      checklistOpen: "SCAR & VERIFICATION",
      checklistProgress: { "NOTIFICATION & EVIDENCE": 3, "SUPPLIER INVESTIGATION": 3, "SCAR & VERIFICATION": 2 },
    },
    {
      source: "PF-11 s12 · proof on the next lot",
      ghost: "Verify",
      type: "Supplier NC",
      id: "#31",
      title: "Seal lot out of spec · Meridian",
      status: "Completed",
      actor: "You",
      event: "Verified effectiveness on the next incoming lot",
      eventDetail: "Documented proof closes the SCAR, not a verbal confirmation",
      checklist: "SCAR & VERIFICATION",
      checklistItems: ["Lot 88-D inspected against CA criteria", "Dimensional results in spec", "Evidence attached to the SCAR"],
      focus: "trace",
      focusTitle: "Effectiveness verified",
      focusRows: ["Documented proof of effectiveness", "Close SCAR"],
      focusAction: "Close SCAR",
      ownershipNote: "More lots monitored if evidence is thin",
      world: SCAR_WORLD,
      checklistOpen: "SCAR & VERIFICATION",
      checklistProgress: { "NOTIFICATION & EVIDENCE": 3, "SUPPLIER INVESTIGATION": 3, "SCAR & VERIFICATION": 3 },
      related: 2,
    },
  ],

  /* PF-2 · Quality Manager runs the annual ISO 13485 audit. */
  "2": [
    {
      source: "PF-2 s1 · schedule notification",
      ghost: "Schedule",
      type: "Audit",
      id: "#12",
      title: "Annual ISO 13485 audit",
      status: "Scheduled",
      actor: "automator",
      event: "Scheduled the annual audit, two weeks out",
      eventDetail: "The notification links straight to the audit record · no navigating",
      checklist: "SCOPE & PLAN",
      checklistItems: ["Scope"],
      focus: "queue",
      focusTitle: "My audits",
      focusRows: [
        "AUD-12 · Annual ISO 13485 · in two weeks",
        "Opens straight from the message",
        "Prior-year findings linked",
      ],
      focusAction: "Open audit record",
      ownershipNote: "Acknowledge now, or defer on conflict",
      world: AUDIT_WORLD,
      queueTile: "My audits",
      checklistProgress: { "SCOPE & PLAN": 0, FINDINGS: 0, CLOSURE: 0 },
    },
    {
      source: "PF-2 s2 · scope on the record",
      ghost: "Scope",
      type: "Audit",
      id: "#12",
      title: "Annual ISO 13485 audit",
      status: "Preparation",
      actor: "You",
      event: "Reviewed the scope and the drafted checklist",
      eventDetail: "Checklist auto-populated from the standard and internal procedure references",
      checklist: "SCOPE & PLAN",
      checklistItems: ["Scope", "Prior-year findings"],
      focus: "record",
      focusTitle: "Scope as drafted",
      focusRows: ["ISO 13485 · full QMS", "Checklist from the standard · prior findings linked"],
      focusAction: "Confirm scope",
      ownershipNote: "Adjust before notifying stakeholders",
      world: AUDIT_WORLD,
      checklistOpen: "SCOPE & PLAN",
      checklistProgress: { "SCOPE & PLAN": 2, FINDINGS: 0, CLOSURE: 0 },
    },
    {
      source: "PF-2 s3 · each recipient gets their sections",
      ghost: "Notify",
      type: "Audit",
      id: "#12",
      title: "Annual ISO 13485 audit",
      status: "Preparation",
      actor: "You",
      event: "Notified the audit lead and stakeholders",
      eventDetail: "Each notification carries the checklist sections that recipient must be ready for",
      checklist: "SCOPE & PLAN",
      checklistItems: ["Auditors and stakeholders"],
      focus: "queue",
      poseVariant: "route",
      focusKicker: "PRE-AUDIT NOTIFICATION",
      focusTitle: "Ready before the walk",
      focusRows: [
        "L. Navarro · Audit lead · full checklist",
        "M. Osei · Production · §7.5 sections",
        "R. Mehta · Document control · §4.2 sections",
      ],
      focusAction: "Notify with their sections",
      ownershipNote: "The recipient list is confirmed here",
      world: AUDIT_WORLD,
      checklistProgress: { "SCOPE & PLAN": 3, FINDINGS: 0, CLOSURE: 0 },
    },
    {
      source: "PF-2 s4 · the floor, on mobile",
      ghost: "Walk",
      type: "Audit",
      id: "#12",
      title: "Annual ISO 13485 audit",
      status: "On Site",
      actor: "You",
      event: "Captured an observation from the floor",
      eventDetail: "Photos attach to the audit record in real time, against the checklist",
      checklist: "FINDINGS",
      checklistItems: ["Observations"],
      focus: "comment",
      focusTitle: "Evidence, in the moment",
      focusRows: ["Observation · photo evidence · checklist §7.5"],
      focusAction: "Attach to checklist",
      ownershipNote: "Finding, or note without a finding",
      world: AUDIT_WORLD,
      checklistOpen: "FINDINGS",
      checklistProgress: { "SCOPE & PLAN": 3, FINDINGS: 1, CLOSURE: 0 },
    },
    {
      source: "PF-2 s5 · the report writes itself",
      ghost: "Record",
      type: "Audit",
      id: "#12",
      title: "Annual ISO 13485 audit",
      status: "On Site",
      actor: "You",
      event: "Recorded the finding with severity and clause",
      eventDetail: "Severity, evidence reference, and the linked clause · the audit report assembles from these",
      checklist: "FINDINGS",
      checklistItems: ["Severity and clause", "Evidence"],
      focus: "review",
      focusTitle: "Finding F-3",
      focusRows: [
        "Severity · Major",
        "Clause · ISO 13485 §7.5.6",
        "Evidence · photo 12 · line 2",
      ],
      focusAction: "Record finding",
      focusAlts: ["Note without finding"],
      ownershipNote: "Severity is the auditor's call",
      world: AUDIT_WORLD,
      checklistOpen: "FINDINGS",
      checklistProgress: { "SCOPE & PLAN": 3, FINDINGS: 3, CLOSURE: 0 },
    },
    {
      source: "PF-2 s6 · CAPA with context preserved",
      ghost: "Route",
      type: "Audit",
      id: "#12",
      title: "Annual ISO 13485 audit",
      status: "Findings",
      actor: "You",
      event: "Routed the major findings to Corrective Actions",
      eventDetail: "The CAPA carries the audit reference, finding text, and linked clause · nothing reconstructed",
      checklist: "CLOSURE",
      checklistItems: ["Routed corrective actions"],
      focus: "comment",
      focusTitle: "Context travels with the finding",
      focusRows: ["CAPA-618 raised from F-3 · audit context attached"],
      focusAction: "Route to CAPA",
      ownershipNote: "Full CAPA or action item, per finding",
      world: AUDIT_WORLD,
      checklistOpen: "CLOSURE",
      checklistProgress: { "SCOPE & PLAN": 3, FINDINGS: 3, CLOSURE: 1 },
    },
    {
      source: "PF-2 s7 · closure on the dashboard",
      ghost: "Track",
      type: "Audit",
      id: "#12",
      title: "Annual ISO 13485 audit",
      status: "Tracking",
      actor: "automator",
      event: "Tracked responses through closure",
      eventDetail: "Notifications fire when responses are due or overdue · no chasing spreadsheet",
      checklist: "CLOSURE",
      checklistItems: ["Responses tracked"],
      focus: "dashboard",
      focusTitle: "Closure aging",
      focusRows: [
        "CAPA-618 · response due Friday",
        "2 action items closed this week",
        "1 overdue · escalated with rationale",
      ],
      focusAction: "Review the programme",
      ownershipNote: "Escalate, or extend with rationale",
      world: AUDIT_WORLD,
      checklistProgress: { "SCOPE & PLAN": 3, FINDINGS: 3, CLOSURE: 2 },
    },
    {
      source: "PF-2 s8 · sign off and lock",
      ghost: "Seal",
      type: "Audit",
      id: "#12",
      title: "Annual ISO 13485 audit",
      status: "Approved",
      actor: "You",
      event: "Signed off the audit under Part 11",
      eventDetail: "Findings addressed, effectiveness verified · the record locks for the year",
      checklist: "CLOSURE",
      checklistItems: ["Part 11 sign-off"],
      focus: "signature",
      focusTitle: "Sign off the audit",
      focusRows: ["All findings addressed", "Audit history file · locked"],
      focusAction: "Apply your signature",
      ownershipNote: "Held only for an outstanding effectiveness review",
      world: AUDIT_WORLD,
      checklistOpen: "CLOSURE",
      checklistProgress: { "SCOPE & PLAN": 3, FINDINGS: 3, CLOSURE: 3 },
    },
  ],
};

/* ============================================================ modules
 * The modules section as camera work: each module tab is a pose over the
 * connected records of ONE story - NC-204 raised on the line, CAPA-612 from
 * complaint CMP-341, audit AUD-12, SCAR-31 at the supplier, and the risk
 * read off NC-204's linked history. One scene instance; tab changes pan. */
export const QMS_MODULE_ARCADE_CONFIGS: Record<string, ArcadeStepConfig> = {
  "non-conformance": {
    source: "PF-5 · capture anatomy",
    ghost: "Capture",
    type: "Non-conformance",
    id: "#204",
    title: "Coating thickness out of spec",
    status: "Open",
    actor: "You",
    event: "Captured from the line with evidence attached",
    eventDetail: "Photos, readings, and ERP context on the record before leaving the line",
    checklist: "CAPTURE & EVIDENCE",
    checklistItems: ["Photos and measurements", "Part and order context"],
    focus: "record",
    focusTitle: "Live before leaving the line",
    focusRows: ["Captured on mobile · Line 2", "Containment tasked · owners notified"],
    focusAction: "Open live record",
    ownershipNote: "One record from detection to closure",
    world: NC_CAPTURE_WORLD,
    checklistOpen: "CAPTURE & EVIDENCE",
  },
  capa: {
    source: "PF-3 · action plan anatomy",
    ghost: "Correct",
    type: "CAPA",
    id: "#612",
    title: "Recurring seal failure",
    status: "Implementation",
    actor: "You",
    event: "Ran the corrective action plan with evidence capture",
    eventDetail: "Every action owned and dated · evidence lands as each completes",
    checklist: "ACTION PLAN",
    checklistItems: ["Retrain sealing crew", "Update SOP-214", "Requalify supplier lot"],
    focus: "tasks",
    focusTitle: "The action plan",
    focusRows: ["Retrain sealing crew · Training", "Update SOP-214 · R. Mehta", "Requalify supplier lot · SQE"],
    focusAction: "Capture evidence",
    ownershipNote: "Closes only on verified effectiveness",
    world: CAPA_WORLD,
    checklistOpen: "ACTION PLAN",
    checklistProgress: { INVESTIGATION: 3, "ACTION PLAN": 2, EFFECTIVENESS: 0 },
  },
  "complaint-handling": {
    source: "PF-3 s1-2 · originating complaint",
    ghost: "Escalate",
    type: "CAPA",
    id: "#612",
    title: "Recurring seal failure",
    status: "Investigation",
    actor: "automator",
    event: "Escalated complaint CMP-341 with its history attached",
    eventDetail: "The complaint, the linked non-conformance, and prior events in one view",
    checklist: "INVESTIGATION",
    checklistItems: ["Originating records"],
    focus: "comment",
    focusTitle: "The complaint travels whole",
    focusRows: ["CMP-341 · customer complaint · linked, updated on close"],
    focusAction: "Open originating record",
    ownershipNote: "No bouncing across systems",
    world: CAPA_WORLD,
    checklistOpen: "INVESTIGATION",
  },
  "audit-management": {
    source: "PF-2 s7 · audit programme",
    ghost: "Audit",
    type: "Audit",
    id: "#12",
    title: "Annual ISO 13485 audit",
    status: "Tracking",
    actor: "automator",
    event: "Tracked findings through closure",
    eventDetail: "Findings linked to clauses · majors routed to CAPA with context preserved",
    checklist: "CLOSURE",
    checklistItems: ["Routed corrective actions", "Responses tracked"],
    focus: "dashboard",
    focusTitle: "Closure aging",
    focusRows: ["CAPA-618 · response due Friday", "2 action items closed this week", "1 overdue · escalated with rationale"],
    focusAction: "Review the programme",
    ownershipNote: "Due and overdue notify by themselves",
    world: AUDIT_WORLD,
  },
  "supplier-quality": {
    source: "PF-11 s11 · SCAR exchange",
    ghost: "Supplier",
    type: "Supplier NC",
    id: "#31",
    title: "Seal lot out of spec · Meridian",
    status: "In Review",
    actor: "You",
    event: "Returned the corrective action plan with structured feedback",
    eventDetail: "The exchange crosses the company boundary on the record, not an email chain",
    checklist: "SCAR & VERIFICATION",
    checklistItems: ["Corrective action plan"],
    focus: "diff",
    focusKicker: "PLAN REVISION",
    focusTitle: "What to fix, exactly",
    focusRows: [
      "Verification · single-lot visual check",
      "Verification · 3 lots, dimensional + records",
      "Timeline extended 2 weeks with rationale",
    ],
    focusAction: "Return for revision",
    ownershipNote: "The supplier sees the full decision trail",
    world: SCAR_WORLD,
    checklistOpen: "SCAR & VERIFICATION",
  },
  "quality-risk-management": {
    source: "PF-5 s6 · severity with linked history",
    ghost: "Assess",
    type: "Non-conformance",
    id: "#204",
    title: "Coating thickness out of spec",
    status: "Assessment",
    actor: "automator",
    event: "Surfaced recurrence for the same part and process",
    eventDetail: "Severity judged with the history in view, not dug out of spreadsheets",
    checklist: "SEVERITY & HISTORY",
    checklistItems: ["Severity", "Prior events"],
    focus: "history",
    focusKicker: "PRIOR EVENTS · PRT-4412",
    focusTitle: "Recurrence in view",
    focusRows: ["NC-204 · Coating thickness · today", "NC-171 · Coating thickness · May 2026", "NC-98 · Adhesion · Jan 2026"],
    focusAction: "Assess severity",
    ownershipNote: "Systemic issues flag themselves",
    world: NC_CAPTURE_WORLD,
    checklistOpen: "SEVERITY & HISTORY",
  },
};

/* keyed by Product Flow id, consumed by LifecycleExplorer's live panel */
export const QMS_ARCADE_FLOW_CONFIGS: Record<string, ArcadeStepConfig[]> = {
  "5": QMS_FLOW_STEP_SCENES["5"],
  "6": QMS_FLOW_STEP_SCENES["6"],
  "7": QMS_FLOW_STEP_SCENES["7"],
  "3": QMS_FLOW_STEP_SCENES["3"],
  "11": QMS_FLOW_STEP_SCENES["11"],
  "2": QMS_FLOW_STEP_SCENES["2"],
};

/* ===================================================== hero journey (arcade)
 * The hero product shot is the arcade itself, same treatment as every
 * product page (shared HeroArcade): poses carrying the headline's claim -
 * a finding isn't closed until the fix is proven. The middle steps are
 * lifted straight from the page's own flows so the hero and the lifecycle
 * section tell the same story with the same facts:
 *   PF-5 · capture at the line and task the containment (NC-204)
 *   PF-6 · put the root cause to the participants (NC-204)
 *   PF-3 · implement the corrective action and prove it off the live
 *          dashboard (CAPA-612) - the escalation is the point: the NC's
 *          discipline hands over to the CAPA's evidence-backed close.
 * Two hero-only bookends are lifted from the QMS product demo (Wistia,
 * 2pdzk5q9iw), same recipe as the DMS hero: the no-code process builder
 * that CONFIGURES the discipline the middle steps ride (demo 0:54-1:09,
 * drag-and-drop field list + add-field palette + approval routing), and
 * the Part 11 signature that CLOSES the record only after the dashboard
 * proves the fix (demo 1:29-1:34, the Apply-your-signature dialog).
 * Labels are the reader's handle on the step. */
const HERO_NC_WORLD: ArcadeFlowWorld = {
  ...NC_CAPTURE_WORLD,
  builder: {
    title: "Non-conformance process",
    note: "The lifecycle every finding walks, configured, not coded.",
    tabs: ["Checklist", "Team", "Statuses", "Privacy", "Reminders"],
    fields: [
      { kind: "Selection", tone: "selection", label: "Basic details" },
      { kind: "Linked field", tone: "linked", label: "Part & work order" },
      { kind: "Text", tone: "text", label: "Problem description" },
      { kind: "File upload", tone: "upload", label: "Photos & readings" },
      { kind: "Picklist", tone: "picklist", label: "Severity" },
      { kind: "Approval", tone: "approval", label: "Disposition approval" },
      { kind: "Generate PDF", tone: "pdf", label: "NC report" },
    ],
    palette: [
      { label: "Approval", note: "Digital signatures on the record", tone: "approval" },
      { label: "File upload", note: "Photos and readings from the line", tone: "upload" },
      { label: "Linked field", note: "Link to another process", tone: "linked" },
      { label: "Picklist", note: "Drop-down selection of items", tone: "picklist" },
      { label: "Revision", note: "Managed revisions of the record", tone: "revision" },
      { label: "Generate PDF", note: "Printable render of the checklist", tone: "pdf" },
    ],
  },
};

const QMS_HERO_BUILD_STEP: ArcadeStepConfig = {
  source: "QMS demo 0:54-1:09 · drag-and-drop builder + add-field palette",
  ghost: "Build",
  type: "Non-conformance",
  id: "#204",
  title: "Coating thickness out of spec",
  status: "Open",
  actor: "You",
  event: "Configured the non-conformance process in the builder",
  eventDetail: "Fields, approval routing and automations · no code",
  checklist: "CAPTURE & EVIDENCE",
  checklistItems: ["Field list", "Approval routing", "Automations"],
  focus: "builder",
  focusTitle: "Disposition approval",
  focusRows: [
    "Signature of the Quality Manager",
    "Contingent on containment complete",
    "On approval · instruction routes to the line",
  ],
  focusAction: "Add field",
  ownershipNote: "Process owner · D. Fontaine",
  world: HERO_NC_WORLD,
  checklistProgress: { "CAPTURE & EVIDENCE": 0, CONTAINMENT: 0, "SEVERITY & HISTORY": 0 },
};

const QMS_HERO_CLOSE_STEP: ArcadeStepConfig = {
  source: "QMS demo 1:29-1:34 · Apply-your-signature dialog (PF-3 s8 close)",
  ghost: "Close",
  type: "CAPA",
  id: "#612",
  title: "Recurring seal failure",
  status: "Closed",
  actor: "You",
  event: "Closed the CAPA under a Part 11 signature",
  eventDetail: "Effectiveness verified against live metrics · the close updates complaint CMP-341",
  checklist: "EFFECTIVENESS",
  checklistItems: ["Recurrence check", "Part 11 sign-off"],
  focus: "signature",
  focusTitle: "Sign off effectiveness",
  focusRows: ["No recurrence in the window", "CMP-341 · updated on close"],
  focusAction: "Apply your signature",
  ownershipNote: "Effective, partially effective, or reopen",
  world: CAPA_WORLD,
  checklistOpen: "EFFECTIVENESS",
  checklistProgress: { INVESTIGATION: 3, "ACTION PLAN": 3, EFFECTIVENESS: 3 },
};

export const QMS_HERO_STEPS: HeroArcadeStep[] = [
  {
    label: "Build it",
    config: QMS_HERO_BUILD_STEP,
  },
  {
    label: "Capture it",
    config: QMS_FLOW_STEP_SCENES["5"][0],
  },
  {
    label: "Contain it",
    config: QMS_FLOW_STEP_SCENES["5"][4],
  },
  {
    label: "Agree the cause",
    config: QMS_FLOW_STEP_SCENES["6"][3],
  },
  {
    label: "Fix it",
    config: QMS_FLOW_STEP_SCENES["3"][5],
  },
  {
    label: "Prove it",
    config: QMS_FLOW_STEP_SCENES["3"][7],
  },
  {
    label: "Close it",
    config: QMS_HERO_CLOSE_STEP,
  },
];
