/* ============================================================================
 * qms-copy.ts - Notion-editable copy overlay for the QMS page.
 * qms-copy.json is regenerated by scripts/notion/sync-copy.mjs from the
 * Copy Fields database in Notion (one row per string, Key "qms/<key>").
 * Every call site keeps its hardcoded fallback: a deleted or blanked Notion
 * row can never blank the page, it just falls back to the shipped string.
 * ========================================================================== */
import raw from "./qms-copy.json";

type CopySlot = { element: string; text: string };

const COPY = raw as Record<string, CopySlot>;

export function qmsCopy(key: string, fallback: string): string {
  const text = COPY[key]?.text?.trim();
  return text || fallback;
}
