/* ============================================================================
 * plm-copy.ts - Notion-editable copy overlay for the PLM page.
 * plm-copy.json is regenerated by scripts/notion/sync-copy.mjs from the
 * Copy Fields database in Notion (one row per string, Key "plm/<key>").
 * Every call site keeps its hardcoded fallback: a deleted or blanked Notion
 * row can never blank the page, it just falls back to the shipped string.
 * ========================================================================== */
import raw from "./plm-copy.json";

type CopySlot = { element: string; text: string };

const COPY = raw as Record<string, CopySlot>;

export function plmCopy(key: string, fallback: string): string {
  const text = COPY[key]?.text?.trim();
  return text || fallback;
}
