/* ----------------------------------------------------------------------------
 * mes-arcade.tsx - persistent-camera arcade journeys for the MES page's
 * Notion-backed Product Flows (PF-31, PF-32, PF-33: the lot's arc from a
 * released work order to a sealed, traceable batch record). Same staging
 * recipe as the DMS and QMS journeys: one app window, one world per record,
 * the camera moves between poses and each step's copy is the Notion Flow
 * Step truth restaged, never invented capability.
 * Fictional dataset: Engineering Industries, work order WO-9021 building
 * PRT-4412 housings (lot 224-B) on line 2 - the same part the QMS journeys
 * investigate, so the two pages tell one continuous story. People:
 * P. Ndiaye (Shop Floor Operator), M. Osei (Production Supervisor),
 * R. Vance (Quality Inspector), S. Okafor (Process Engineering).
 * Server module, no state.
 * -------------------------------------------------------------------------- */

import {
  type ArcadeFlowWorld,
  type ArcadeStepConfig,
} from "../_shared/arcade/arcade";
import { type HeroArcadeStep } from "../_shared/arcade/hero-arcade";

/* ============================================================ PF-31 world
 * The work order as the operator runs it: traveller, checks, batch entries.
 * Checklist sections are the record's stable anatomy; steps only open
 * sections and advance completion. */
const TRAVELLER_WORLD: ArcadeFlowWorld = {
  team: "Engineering Industries",
  recordNoun: "Work Order",
  owner: "P. Ndiaye",
  ownerInitials: "PN",
  participants: ["PN", "MO", "+2"],
  participantsLabel: "P. Ndiaye, M. Osei, and two others",
  recordKicker: "ETRAVELLER",
  context: {
    initials: "MO",
    name: "M. Osei",
    time: "06:52",
    message: "Released WO-9021 to line 2 with the traveller attached.",
    detail: "Routing Rev C · materials staged · lot 224-B",
  },
  inboxNeighbors: [
    { title: "First article inspection", time: "07:15", detail: "FAI-52 · fixture 2 · due", kind: "Inspection" },
    { title: "Line clearance", time: "06:40", detail: "Line 2 · cleared for lot 224-B", kind: "Checklist" },
    { title: "Non-conformance", time: "Yesterday", detail: "NC-204 · coating · dispositioned", kind: "Quality event" },
  ],
  homeTiles: [
    { label: "Work orders", count: 5 },
    { label: "My inspections", count: 3 },
    { label: "Exceptions", count: 1 },
  ],
  checklistTitle: "eTraveller",
  checklistSections: [
    {
      title: "ROUTING & SETUP",
      items: [
        { label: "Routing step 3 of 8", note: "Coating · line 2" },
        { label: "Work instruction", note: "SOP-118 Rev D · current" },
        { label: "Materials staged", note: "Lot 224-B · verified" },
      ],
    },
    {
      title: "IN-PROCESS CHECKS",
      items: [
        { label: "Thickness · 3 samples", note: "Acceptance criteria attached" },
        { label: "Visual inspection", note: "Surface · station capture" },
        { label: "Torque check", note: "Fixture 2" },
      ],
    },
    {
      title: "BATCH RECORD",
      items: [
        {
          label: "Thickness reading",
          kind: "field",
          value: "41.2 µm · in spec",
          note: "Sealed 10:42 · P. Ndiaye",
        },
        { label: "Lot genealogy", note: "Consumed lots linked" },
        { label: "Step signature", kind: "approval", signer: "P. Ndiaye", state: "Signed", note: "21 CFR Part 11" },
      ],
    },
  ],
};

/* ============================================================ PF-32 world
 * The first article at the bench: characteristics against the control plan,
 * a hold on the failed reading, and a release on evidence. */
const FAI_WORLD: ArcadeFlowWorld = {
  team: "Engineering Industries",
  recordNoun: "First Article",
  owner: "R. Vance",
  ownerInitials: "RV",
  participants: ["RV", "MO", "SO"],
  participantsLabel: "R. Vance, M. Osei, and S. Okafor",
  recordKicker: "FIRST ARTICLE INSPECTION",
  context: {
    initials: "MO",
    name: "M. Osei",
    time: "07:15",
    message: "First article off line 2 for WO-9021.",
    detail: "FAI-52 · fixture 2 · control plan Rev C attached",
  },
  inboxNeighbors: [
    { title: "Work order", time: "06:52", detail: "WO-9021 · lot 224-B · in process", kind: "Work Order" },
    { title: "In-process inspection", time: "Yesterday", detail: "INS-0871 · passed", kind: "Inspection" },
    { title: "Non-conformance", time: "Yesterday", detail: "NC-204 · coating · dispositioned", kind: "Quality event" },
  ],
  homeTiles: [
    { label: "First articles", count: 2 },
    { label: "My inspections", count: 3 },
    { label: "Holds", count: 1 },
  ],
  checklistTitle: "First Article",
  checklistSections: [
    {
      title: "CHARACTERISTICS",
      items: [
        { label: "Dimensions · 12 characteristics", note: "Criteria from control plan Rev C" },
        { label: "Coating thickness · 45-55 µm", note: "3 samples · fixture 2" },
        { label: "Seal fit force · 12-18 N", note: "3 samples" },
      ],
    },
    {
      title: "DISPOSITION",
      items: [
        {
          label: "Hold reason",
          kind: "field",
          value: "CH-07 seal fit 19.4 N · above the 18 N limit",
          note: "Raised at the bench · line held",
        },
        { label: "Supervisor review", note: "Routed with the evidence attached" },
        { label: "Corrective adjustment", note: "Setup offset corrected · re-measure" },
      ],
    },
    {
      title: "RELEASE",
      items: [
        { label: "First article approval", kind: "approval", signer: "R. Vance", state: "Signed", note: "Disposition sealed" },
        { label: "Run released", note: "Line 2 resumes on approval" },
      ],
    },
  ],
};

/* ============================================================ PF-33 world
 * The batch record at end of lot: review by exception, the genealogy, and
 * the Part 11 seal that releases the lot. */
const EBR_WORLD: ArcadeFlowWorld = {
  team: "Engineering Industries",
  recordNoun: "Batch Record",
  owner: "M. Osei",
  ownerInitials: "MO",
  participants: ["MO", "PN", "RV"],
  participantsLabel: "M. Osei, P. Ndiaye, and R. Vance",
  recordKicker: "ELECTRONIC BATCH RECORD",
  context: {
    initials: "PN",
    name: "P. Ndiaye",
    time: "14:20",
    message: "Final operation closed on WO-9021.",
    detail: "Lot 224-B · batch record complete · 3 exceptions flagged",
  },
  inboxNeighbors: [
    { title: "Work order", time: "14:20", detail: "WO-9021 · all operations closed", kind: "Work Order" },
    { title: "First article inspection", time: "09:40", detail: "FAI-52 · approved", kind: "Inspection" },
    { title: "Line clearance", time: "06:40", detail: "Line 2 · cleared for lot 224-B", kind: "Checklist" },
  ],
  homeTiles: [
    { label: "Exceptions", count: 3 },
    { label: "Lots at end of line", count: 2 },
    { label: "Pending approvals", count: 2 },
  ],
  checklistTitle: "Batch Record · Lot 224-B",
  checklistSections: [
    {
      title: "EXCEPTIONS",
      items: [
        {
          label: "Missing torque entry",
          kind: "field",
          value: "Station 4 · returned for capture",
          note: "Resolved on the record",
        },
        { label: "Out-of-trend thickness", note: "41.2 µm · in spec · trend flagged" },
        { label: "Missing signature · op 30", note: "Signed at the station" },
      ],
    },
    {
      title: "GENEALOGY",
      items: [
        { label: "Consumed lots", note: "224-A resin · 198-C seals" },
        { label: "Equipment", note: "Line 2 · fixture 2 · calibrated" },
        { label: "Operators", note: "3 signed operations" },
      ],
    },
    {
      title: "SEAL & RELEASE",
      items: [
        { label: "Release signature", kind: "approval", signer: "M. Osei", state: "Signed", note: "21 CFR Part 11" },
        { label: "QR codes", note: "QR-224B-01…04 generated" },
        { label: "Distribution", note: "Traceable downstream by lot" },
      ],
    },
  ],
};

/* ============================================================ modules
 * The modules section as camera work: five module tabs, five poses on the
 * SAME work order WO-9021 - genuinely one continuous record from release to
 * the sealed lot. One scene instance; tab changes pan the camera. */
export const MES_MODULE_ARCADE_CONFIGS: Record<string, ArcadeStepConfig> = {
  "work-order-management": {
    source: "MES modules · release queue",
    ghost: "Release",
    type: "Work Order",
    id: "#9021",
    title: "PRT-4412 housing · lot 224-B",
    status: "Released",
    actor: "automator",
    event: "Released the work order to line 2",
    eventDetail: "Traveller, routing, and staged materials linked · no printed packet",
    checklist: "ROUTING & SETUP",
    checklistItems: ["Routing step", "Materials staged"],
    focus: "queue",
    focusTitle: "Work orders",
    focusRows: [
      "WO-9021 · PRT-4412 housing · released",
      "Traveller attached · routing Rev C",
      "Materials staged · lot 224-B",
    ],
    focusAction: "Start traveller",
    ownershipNote: "Everything staged before the line starts",
    world: TRAVELLER_WORLD,
    queueTile: "Work orders",
  },
  etravellers: {
    source: "MES modules · traveller context",
    ghost: "Travel",
    type: "Work Order",
    id: "#9021",
    title: "PRT-4412 housing · lot 224-B",
    status: "In Process",
    actor: "You",
    event: "Opened the eTraveller at routing step 3",
    eventDetail: "The controlled work instruction at its current revision, on the record",
    checklist: "ROUTING & SETUP",
    checklistItems: ["Routing step", "Work instruction"],
    focus: "record",
    focusTitle: "Right step, right revision",
    focusRows: ["Step 3 of 8 · coating · line 2", "SOP-118 Rev D linked · current by construction"],
    focusAction: "Begin step",
    ownershipNote: "Nothing fetched from a binder",
    world: TRAVELLER_WORLD,
    checklistOpen: "ROUTING & SETUP",
  },
  "fai-control-plan-execution": {
    source: "MES modules · first article",
    ghost: "Approve",
    type: "Work Order",
    id: "#9021",
    title: "PRT-4412 housing · lot 224-B",
    status: "In Process",
    actor: "You",
    event: "Ran the first article against the control plan",
    eventDetail: "Criteria from the plan · disposition on the record before the run",
    checklist: "IN-PROCESS CHECKS",
    checklistItems: ["Thickness · 3 samples", "Torque check"],
    focus: "review",
    focusTitle: "First article · fixture 2",
    focusRows: [
      "FAI-52 · dimensions 12 of 12 in spec",
      "Control plan · coating step criteria",
      "Disposition · approved to run",
    ],
    focusAction: "Approve first article",
    focusAlts: ["Hold the line"],
    ownershipNote: "The run starts only on approval",
    world: TRAVELLER_WORLD,
    checklistOpen: "IN-PROCESS CHECKS",
  },
  "inspections-forms-checklists": {
    source: "MES modules · station capture",
    ghost: "Inspect",
    type: "Work Order",
    id: "#9021",
    title: "PRT-4412 housing · lot 224-B",
    status: "In Process",
    actor: "You",
    event: "Ran the in-process checks at the station",
    eventDetail: "Acceptance criteria attached to each task · captured as it happens",
    checklist: "IN-PROCESS CHECKS",
    checklistItems: ["Thickness · 3 samples", "Visual inspection", "Torque check"],
    focus: "tasks",
    focusTitle: "In-process checks",
    focusRows: [
      "Thickness · 3 samples · Station 2",
      "Visual inspection · surface",
      "Torque check · fixture 2",
    ],
    focusAction: "Capture results",
    ownershipNote: "A failed criterion holds the step",
    world: TRAVELLER_WORLD,
    checklistOpen: "IN-PROCESS CHECKS",
    checklistProgress: { "ROUTING & SETUP": 3, "IN-PROCESS CHECKS": 2, "BATCH RECORD": 0 },
  },
  "electronic-batch-lot-records": {
    source: "MES modules · the record builds itself",
    ghost: "Seal",
    type: "Work Order",
    id: "#9021",
    title: "PRT-4412 housing · lot 224-B",
    status: "In Process",
    actor: "You",
    event: "Entering the reading on the batch record",
    eventDetail: "Operator and timestamp seal to the entry · genealogy links as lots are consumed",
    checklist: "BATCH RECORD",
    checklistItems: ["Thickness reading", "Lot genealogy", "Step signature"],
    focus: "checklist",
    focusTitle: "The record builds as the work happens",
    focusRows: ["Nothing assembled at the end of the lot"],
    focusAction: "Seal entry",
    ownershipNote: "Review-by-exception, not a paper chase",
    world: TRAVELLER_WORLD,
    checklistOpen: "BATCH RECORD",
    checklistEntry: { section: "BATCH RECORD", item: "Thickness reading" },
  },
};

/* ============================================================ scenes
 * One entry per Notion flow id; one scene per Flow Step, in step order. */
export const MES_ARCADE_FLOW_CONFIGS: Record<string, ArcadeStepConfig[]> = {
  /* -------- PF-31 · Shop Floor Operator runs the eTraveller ------------- */
  "31": [
    {
      source: "PF-31 s1 · released to the queue",
      ghost: "Start",
      type: "Work Order",
      id: "#9021",
      title: "PRT-4412 housing · lot 224-B",
      status: "Released",
      actor: "automator",
      event: "Released the work order to line 2",
      eventDetail: "Traveller, routing, and staged materials linked · no printed packet",
      checklist: "ROUTING & SETUP",
      checklistItems: ["Routing step", "Work instruction", "Materials staged"],
      focus: "queue",
      focusTitle: "Work orders",
      focusRows: [
        "WO-9021 · PRT-4412 housing · released",
        "Traveller attached · routing Rev C",
        "Materials staged · lot 224-B",
      ],
      focusAction: "Start traveller",
      ownershipNote: "Query the release if staging is short",
      world: TRAVELLER_WORLD,
      queueTile: "Work orders",
      checklistProgress: { "ROUTING & SETUP": 1, "IN-PROCESS CHECKS": 0, "BATCH RECORD": 0 },
    },
    {
      source: "PF-31 s2 · traveller in context",
      ghost: "Open",
      type: "Work Order",
      id: "#9021",
      title: "PRT-4412 housing · lot 224-B",
      status: "In Process",
      actor: "You",
      event: "Opened the eTraveller at routing step 3",
      eventDetail: "Controlled work instruction at its current revision, on the record",
      checklist: "ROUTING & SETUP",
      checklistItems: ["Routing step", "Work instruction"],
      focus: "record",
      focusTitle: "Right step, right revision",
      focusRows: ["Step 3 of 8 · coating · line 2", "SOP-118 Rev D linked · current by construction"],
      focusAction: "Begin step",
      ownershipNote: "Nothing fetched from a binder",
      world: TRAVELLER_WORLD,
      checklistOpen: "ROUTING & SETUP",
      checklistProgress: { "ROUTING & SETUP": 3, "IN-PROCESS CHECKS": 0, "BATCH RECORD": 0 },
    },
    {
      source: "PF-31 s3 · checks as structured tasks",
      ghost: "Check",
      type: "Work Order",
      id: "#9021",
      title: "PRT-4412 housing · lot 224-B",
      status: "In Process",
      actor: "You",
      event: "Ran the step's checks as structured tasks",
      eventDetail: "Acceptance criteria attached to each task · a failed criterion holds the step",
      checklist: "IN-PROCESS CHECKS",
      checklistItems: ["Thickness · 3 samples", "Visual inspection", "Torque check"],
      focus: "tasks",
      focusTitle: "In-process checks",
      focusRows: [
        "Thickness · 3 samples · Station 2",
        "Visual inspection · surface",
        "Torque check · fixture 2",
      ],
      focusAction: "Capture results",
      ownershipNote: "A failed criterion holds the step",
      world: TRAVELLER_WORLD,
      checklistOpen: "IN-PROCESS CHECKS",
      checklistProgress: { "ROUTING & SETUP": 3, "IN-PROCESS CHECKS": 2, "BATCH RECORD": 0 },
    },
    {
      source: "PF-31 s4 · the record builds itself",
      ghost: "Seal",
      type: "Work Order",
      id: "#9021",
      title: "PRT-4412 housing · lot 224-B",
      status: "In Process",
      actor: "You",
      event: "Entering the reading on the batch record",
      eventDetail: "Operator and timestamp seal to the entry · genealogy links as lots are consumed",
      checklist: "BATCH RECORD",
      checklistItems: ["Reading 41.2 µm · sealed 10:42 · PN", "Lot 224-B consumed · genealogy linked", "Equipment · coater 2 · verified"],
      focus: "checklist",
      focusTitle: "The record builds as the work happens",
      focusRows: ["Nothing assembled at the end of the lot", "Close step"],
      focusAction: "Seal entry",
      ownershipNote: "Nothing assembled at the end of the lot",
      world: TRAVELLER_WORLD,
      checklistOpen: "BATCH RECORD",
      checklistEntry: { section: "BATCH RECORD", item: "Thickness reading" },
      checklistProgress: { "ROUTING & SETUP": 3, "IN-PROCESS CHECKS": 3, "BATCH RECORD": 0 },
    },
    {
      source: "PF-31 s5 · sign the operation, hand off the record",
      ghost: "Sign",
      type: "Work Order",
      id: "#9021",
      title: "PRT-4412 housing · lot 224-B",
      status: "In Process",
      actor: "You",
      event: "Signing step 3; the traveller advances to station 4",
      eventDetail: "The handoff carries the record, not a verbal summary",
      checklist: "BATCH RECORD",
      checklistItems: ["Entries sealed", "Lot genealogy", "Step signature"],
      focus: "signature",
      focusTitle: "Sign step 3 · coating",
      focusRows: ["Operation complete · evidence sealed", "Next station receives the context"],
      focusAction: "Apply your signature",
      ownershipNote: "An exception would be flagged before handoff",
      world: TRAVELLER_WORLD,
      checklistOpen: "BATCH RECORD",
      checklistProgress: { "ROUTING & SETUP": 3, "IN-PROCESS CHECKS": 3, "BATCH RECORD": 2 },
    },
  ],

  /* -------- PF-32 · Quality Inspector proves the first article ---------- */
  "32": [
    {
      source: "PF-32 s1 · FAI on the queue",
      ghost: "Pick",
      type: "First Article",
      id: "#52",
      title: "FAI-52 · PRT-4412 · fixture 2",
      status: "Pending",
      actor: "automator",
      event: "First article inspection fired for WO-9021",
      eventDetail: "Control plan characteristics and acceptance criteria attached to the task",
      checklist: "CHARACTERISTICS",
      checklistItems: ["Dimensions · 12 characteristics", "Coating thickness", "Seal fit force"],
      focus: "queue",
      focusTitle: "First articles",
      focusRows: [
        "FAI-52 · PRT-4412 housing · due",
        "Characteristics attached · control plan Rev C",
        "Line 2 waiting on the result",
      ],
      focusAction: "Open first article",
      ownershipNote: "The run waits on this call",
      world: FAI_WORLD,
      queueTile: "First articles",
      checklistProgress: { CHARACTERISTICS: 0, DISPOSITION: 0, RELEASE: 0 },
    },
    {
      source: "PF-32 s2 · measured against the plan",
      ghost: "Measure",
      type: "First Article",
      id: "#52",
      title: "FAI-52 · PRT-4412 · fixture 2",
      status: "In Review",
      actor: "You",
      event: "Measuring the characteristics against the control plan",
      eventDetail: "Each measurement captured against its tolerance as it is taken · no paper transcription",
      checklist: "CHARACTERISTICS",
      checklistItems: ["Dimensions · 12 characteristics", "Coating thickness · 45-55 µm", "Seal fit force · 12-18 N"],
      focus: "tasks",
      focusTitle: "Characteristic checks",
      focusRows: [
        "Dimensions · 12 characteristics · CMM",
        "Coating thickness · 3 samples",
        "Seal fit force · 3 samples · fixture 2",
      ],
      focusAction: "Capture measurements",
      ownershipNote: "Criteria sit beside each entry",
      world: FAI_WORLD,
      checklistOpen: "CHARACTERISTICS",
      checklistProgress: { CHARACTERISTICS: 2, DISPOSITION: 0, RELEASE: 0 },
    },
    {
      source: "PF-32 s3 · out of tolerance, line held",
      ghost: "Hold",
      type: "First Article",
      id: "#52",
      title: "FAI-52 · PRT-4412 · fixture 2",
      status: "On Hold",
      actor: "You",
      event: "Flagged CH-07 and held the run",
      eventDetail: "The failed characteristic raises the hold in real time · not from an inbox",
      checklist: "DISPOSITION",
      checklistItems: ["Hold reason", "Supervisor review"],
      focus: "review",
      focusTitle: "CH-07 · seal fit force",
      focusRows: [
        "Measured · 19.4 N",
        "Limit · 12-18 N",
        "Status · out of tolerance",
      ],
      focusAction: "Hold the run",
      focusAlts: ["Pass with deviation"],
      ownershipNote: "The line is not running on a bad setup",
      world: FAI_WORLD,
      checklistOpen: "DISPOSITION",
      checklistProgress: { CHARACTERISTICS: 3, DISPOSITION: 1, RELEASE: 0 },
    },
    {
      source: "PF-32 s4 · disposition with the evidence",
      ghost: "Route",
      type: "First Article",
      id: "#52",
      title: "FAI-52 · PRT-4412 · fixture 2",
      status: "On Hold",
      actor: "You",
      event: "Escalated the disposition with the evidence attached",
      eventDetail: "Measurement, characteristic, and criterion in one thread · decided where the evidence is",
      checklist: "DISPOSITION",
      checklistItems: ["Hold reason", "Supervisor review", "Corrective adjustment"],
      focus: "queue",
      poseVariant: "route",
      focusKicker: "DISPOSITION REVIEW",
      focusTitle: "The call, made on the record",
      focusRows: [
        "M. Osei · Production Supervisor · required",
        "S. Okafor · Process Engineering · required",
        "R. Vance · Quality Inspector · evidence attached",
      ],
      focusAction: "Route disposition",
      ownershipNote: "Rework the setup, or scrap and reset",
      world: FAI_WORLD,
      checklistProgress: { CHARACTERISTICS: 3, DISPOSITION: 2, RELEASE: 0 },
    },
    {
      source: "PF-32 s5 · proven, released",
      ghost: "Release",
      type: "First Article",
      id: "#52",
      title: "FAI-52 · PRT-4412 · fixture 2",
      status: "Approved",
      actor: "You",
      event: "Approved the first article; the run is released",
      eventDetail: "The disposition and its evidence seal to the record",
      checklist: "RELEASE",
      checklistItems: ["CH-07 re-measured · 15.1 N · in spec", "12 of 12 characteristics in spec", "Disposition sealed with evidence"],
      focus: "trace",
      focusTitle: "First article proven",
      focusRows: ["Where the auditor will look", "Release the run"],
      focusAction: "Release the run",
      ownershipNote: "Line 2 resumes on approval",
      world: FAI_WORLD,
      checklistOpen: "RELEASE",
      checklistProgress: { CHARACTERISTICS: 3, DISPOSITION: 3, RELEASE: 2 },
      related: 2,
    },
  ],

  /* -------- PF-33 · Production Supervisor seals the batch record -------- */
  "33": [
    {
      source: "PF-33 s1 · review by exception",
      ghost: "Review",
      type: "Batch Record",
      id: "#224B",
      title: "Lot 224-B · PRT-4412 housing",
      status: "In Review",
      actor: "automator",
      event: "Lot 224-B reached end of line with 3 exceptions flagged",
      eventDetail: "The clean entries do not ask for time",
      checklist: "EXCEPTIONS",
      checklistItems: ["Missing torque entry", "Out-of-trend thickness", "Missing signature · op 30"],
      focus: "queue",
      focusTitle: "Exceptions",
      focusRows: [
        "Missing torque entry · station 4",
        "Out-of-trend thickness · op 20",
        "Missing signature · op 30",
      ],
      focusAction: "Review exceptions",
      ownershipNote: "Which exception to clear first",
      world: EBR_WORLD,
      queueTile: "Exceptions",
      checklistProgress: { EXCEPTIONS: 0, GENEALOGY: 0, "SEAL & RELEASE": 0 },
    },
    {
      source: "PF-33 s2 · each exception, on the record",
      ghost: "Resolve",
      type: "Batch Record",
      id: "#224B",
      title: "Lot 224-B · PRT-4412 housing",
      status: "In Review",
      actor: "You",
      event: "Resolving the flagged entries where they live",
      eventDetail: "Who captured it, at which step, against which criterion · in view",
      checklist: "EXCEPTIONS",
      checklistItems: ["Missing torque entry", "Out-of-trend thickness"],
      focus: "review",
      focusTitle: "Exception · missing torque entry",
      focusRows: [
        "Captured · station 4 · op 40",
        "Criterion · 4.2-4.8 N·m",
        "Resolution · returned for capture",
      ],
      focusAction: "Send back to station",
      focusAlts: ["Accept with justification"],
      ownershipNote: "The resolution lands next to the entry",
      world: EBR_WORLD,
      checklistOpen: "EXCEPTIONS",
      checklistProgress: { EXCEPTIONS: 2, GENEALOGY: 0, "SEAL & RELEASE": 0 },
    },
    {
      source: "PF-33 s3 · the genealogy closes",
      ghost: "Trace",
      type: "Batch Record",
      id: "#224B",
      title: "Lot 224-B · PRT-4412 housing",
      status: "In Review",
      actor: "You",
      event: "Verified the lot genealogy end to end",
      eventDetail: "Checked on the record · not reconciled across ERP, paper, and a logbook",
      checklist: "GENEALOGY",
      checklistItems: ["Consumed lots · 224-A resin · 198-C seals", "Equipment · line 2 · fixture 2 · calibrated", "Operators · 3 signed operations"],
      focus: "trace",
      focusTitle: "Genealogy closed",
      focusRows: ["No orphan entries", "Ready to seal"],
      focusAction: "Confirm genealogy",
      ownershipNote: "No orphan entries",
      world: EBR_WORLD,
      checklistOpen: "GENEALOGY",
      checklistProgress: { EXCEPTIONS: 3, GENEALOGY: 3, "SEAL & RELEASE": 0 },
    },
    {
      source: "PF-33 s4 · sealed under Part 11",
      ghost: "Seal",
      type: "Batch Record",
      id: "#224B",
      title: "Lot 224-B · PRT-4412 housing",
      status: "In Review",
      actor: "You",
      event: "Sealing the reconciled batch record",
      eventDetail: "Signer, meaning, and timestamp · every entry carries who, when, and against what criterion",
      checklist: "SEAL & RELEASE",
      checklistItems: ["Release signature", "QR codes"],
      focus: "signature",
      focusTitle: "Seal batch record · lot 224-B",
      focusRows: ["Exceptions resolved · genealogy closed", "8 of 8 operations signed"],
      focusAction: "Confirm and sign",
      ownershipNote: "Review-by-exception, not a paper chase",
      world: EBR_WORLD,
      checklistOpen: "SEAL & RELEASE",
      checklistProgress: { EXCEPTIONS: 3, GENEALOGY: 3, "SEAL & RELEASE": 1 },
    },
    {
      source: "PF-33 s5 · released, traceable by lot",
      ghost: "Ship",
      type: "Batch Record",
      id: "#224B",
      title: "Lot 224-B · PRT-4412 housing",
      status: "Released",
      actor: "automator",
      event: "Lot 224-B released with QR-coded traceability",
      eventDetail: "An auditor's question about this lot starts and ends at one record",
      checklist: "SEAL & RELEASE",
      checklistItems: ["Release signature", "QR codes", "Distribution"],
      focus: "record",
      focusTitle: "Sealed and released",
      focusRows: ["Lot 224-B · sealed under Part 11", "QR-224B-01…04 · traceable through distribution"],
      focusAction: "Track downstream",
      ownershipNote: "Traceable by lot, downstream",
      world: EBR_WORLD,
      checklistOpen: "SEAL & RELEASE",
      checklistProgress: { EXCEPTIONS: 3, GENEALOGY: 3, "SEAL & RELEASE": 3 },
      signedItems: [
        {
          name: "M. Osei",
          initials: "MO",
          role: "Production Supervisor · Release",
          approvalId: "EBR-224B-SEAL",
          time: "15:02",
        },
      ],
      related: 3,
    },
  ],
};

/* ===================================================== hero journey (arcade)
 * The hero product shot is the arcade itself, same treatment as every
 * product page (shared HeroArcade): moments of the lot's life carrying the
 * headline's claim - what happened on the floor is a record, not a memory.
 * Steps 2-5 are the PF-31 operator journey; the closing shot is the PF-33
 * Part 11 seal, so the hero spans release to sealed lot with the same facts
 * as the lifecycle section. Two hero-only bookends follow the DMS/QMS hero
 * recipe, grounded in the MES combined customer video (Wistia, af5axaaz):
 * the no-code process builder that CONFIGURES the traveller the middle
 * steps ride (the record anatomy at 0:02, restaged in the builder grammar
 * the QMS demo 0:54-1:09 established), and the live manufacturing dashboard
 * the running lot reports into (video 0:24-0:36 NC closure TAT chart with
 * its 4-5-weeks-to-7.2-days trend, 2:38 Manufacturing Overview with the
 * saved-report rail). Labels are the reader's handle on the step. */
const HERO_TRAVELLER_WORLD: ArcadeFlowWorld = {
  ...TRAVELLER_WORLD,
  builder: {
    title: "eTraveller process",
    note: "The traveller every work order walks, configured, not coded.",
    tabs: ["Checklist", "Team", "Statuses", "Privacy", "Reminders"],
    fields: [
      { kind: "Selection", tone: "selection", label: "Basic details" },
      { kind: "Linked field", tone: "linked", label: "Routing & work instruction" },
      { kind: "Linked field", tone: "linked", label: "Materials & lot genealogy" },
      { kind: "Text", tone: "text", label: "In-process checks · criteria" },
      { kind: "File upload", tone: "upload", label: "Station photos & readings" },
      { kind: "Approval", tone: "approval", label: "Step signature" },
      { kind: "Generate PDF", tone: "pdf", label: "Batch record render" },
    ],
    palette: [
      { label: "Approval", note: "Digital signatures on the record", tone: "approval" },
      { label: "File upload", note: "Photos and readings from the line", tone: "upload" },
      { label: "Linked field", note: "Link to another process", tone: "linked" },
      { label: "Picklist", note: "Drop-down selection of items", tone: "picklist" },
      { label: "Revision", note: "Managed revisions of the record", tone: "revision" },
      { label: "Generate PDF", note: "Printable render of the checklist", tone: "pdf" },
    ],
  },
};

const HERO_EBR_WORLD: ArcadeFlowWorld = {
  ...EBR_WORLD,
  reports: {
    title: "Manufacturing overview",
    kpis: [
      { label: "Active work orders", value: "24", note: "5 released today" },
      { label: "On-time delivery", value: "96%", note: "12-month rolling" },
      { label: "NC closure TAT", value: "7.2d", note: "down from 4-5 weeks" },
      { label: "Open exceptions", value: "3", note: "all on lot 224-B" },
    ],
    panels: [
      { label: "Non-conformance closure TAT", kind: "bars" },
      { label: "Rework cases over time", kind: "lines" },
      { label: "Active production by department", kind: "donut" },
    ],
  },
};

const MES_HERO_BUILD_STEP: ArcadeStepConfig = {
  source: "MES video 0:02 record anatomy · builder bookend (QMS demo 0:54-1:09 grammar)",
  ghost: "Build",
  type: "Work Order",
  id: "#9021",
  title: "PRT-4412 housing · lot 224-B",
  status: "Open",
  actor: "You",
  event: "Configured the eTraveller in the builder",
  eventDetail: "Routing, checks, signatures and the batch record · no code",
  checklist: "ROUTING & SETUP",
  checklistItems: ["Field list", "Approval routing", "Automations"],
  focus: "builder",
  focusTitle: "Step signature",
  focusRows: [
    "Signature of the station operator",
    "Contingent on in-process checks complete",
    "On signature · the traveller advances a station",
  ],
  focusAction: "Add field",
  ownershipNote: "Process owner · S. Okafor",
  world: HERO_TRAVELLER_WORLD,
  checklistProgress: { "ROUTING & SETUP": 0, "IN-PROCESS CHECKS": 0, "BATCH RECORD": 0 },
};

const MES_HERO_DASH_STEP: ArcadeStepConfig = {
  source: "MES video 0:24-0:36 + 2:38 · NC closure TAT chart + Manufacturing Overview",
  ghost: "Watch",
  type: "Batch Record",
  id: "#224B",
  title: "Lot 224-B · PRT-4412 housing",
  status: "In Review",
  actor: "automator",
  event: "The floor reports itself while the lot runs",
  eventDetail: "Closure times, work orders and exceptions · live from every record, no export",
  checklist: "EXCEPTIONS",
  checklistItems: ["Missing torque entry", "Out-of-trend thickness"],
  focus: "dashboard",
  focusTitle: "Non-conformance closure TAT",
  focusRows: [
    "Apr-Jun · closures took 4-5 weeks",
    "This quarter · 7.2 days median",
    "Every bar opens the records behind it",
  ],
  focusAction: "Open the report",
  ownershipNote: "No spreadsheet was assembled for this",
  world: HERO_EBR_WORLD,
  checklistProgress: { EXCEPTIONS: 2, GENEALOGY: 0, "SEAL & RELEASE": 0 },
};

export const MES_HERO_STEPS: HeroArcadeStep[] = [
  {
    label: "Build the process",
    config: MES_HERO_BUILD_STEP,
  },
  {
    label: "Pick up the order",
    config: MES_ARCADE_FLOW_CONFIGS["31"][0],
  },
  {
    label: "Open the traveller",
    config: MES_ARCADE_FLOW_CONFIGS["31"][1],
  },
  {
    label: "Run the checks",
    config: MES_ARCADE_FLOW_CONFIGS["31"][2],
  },
  {
    label: "Seal the entry",
    config: MES_ARCADE_FLOW_CONFIGS["31"][3],
  },
  {
    label: "Watch the floor",
    config: MES_HERO_DASH_STEP,
  },
  {
    label: "Release the lot",
    config: MES_ARCADE_FLOW_CONFIGS["33"][3],
  },
];
