/* ----------------------------------------------------------------------------
 * mes-arcade.tsx - DRAFT arcade journey for the MES page. The Product Flows
 * DB in Notion has no MES-module flows yet, so this flow is page-owned and
 * labeled draft: the step rows below are written in the DB's own idiom
 * (name / what happens / decision / role / primitives) so they can be
 * ratified into Notion nearly verbatim, at which point the page switches to
 * the Notion-backed copy and this file keeps only the scene configs.
 * Fictional dataset: Engineering Industries, work order WO-9021 building
 * PRT-4412 housings (lot 224-B) on line 2 - the same part the QMS journeys
 * investigate, so the two pages tell one continuous story.
 * Server module, no state.
 * -------------------------------------------------------------------------- */

import {
  type ArcadeFlowWorld,
  type ArcadeStepConfig,
} from "../_shared/arcade/arcade";
import { type ProductFlow } from "../_shared/product-flows";

const DRAFT_NOTE =
  "Draft journey staged for review. The matching Product Flow rows are proposed for the Notion DB; this flow goes Notion-backed the moment they land.";

/* ============================================================ world */
const TRAVELLER_WORLD: ArcadeFlowWorld = {
  team: "Engineering Industries",
  recordNoun: "Work Order",
  owner: "P. Ndiaye",
  ownerInitials: "PN",
  participants: ["PN", "MO", "+2"],
  participantsLabel: "P. Ndiaye, M. Osei, and two others",
  recordKicker: "ETRAVELLER",
  context: {
    initials: "MO",
    name: "M. Osei",
    time: "06:52",
    message: "Released WO-9021 to line 2 with the traveller attached.",
    detail: "Routing Rev C · materials staged · lot 224-B",
  },
  inboxNeighbors: [
    { title: "First article inspection", time: "07:15", detail: "FAI-52 · fixture 2 · due", kind: "Inspection" },
    { title: "Line clearance", time: "06:40", detail: "Line 2 · cleared for lot 224-B", kind: "Checklist" },
    { title: "Non-conformance", time: "Yesterday", detail: "NC-204 · coating · dispositioned", kind: "Quality event" },
  ],
  homeTiles: [
    { label: "Work orders", count: 5 },
    { label: "My inspections", count: 3 },
    { label: "Exceptions", count: 1 },
  ],
  checklistTitle: "eTraveller",
  checklistSections: [
    {
      title: "ROUTING & SETUP",
      items: [
        { label: "Routing step 3 of 8", note: "Coating · line 2" },
        { label: "Work instruction", note: "SOP-118 Rev D · current" },
        { label: "Materials staged", note: "Lot 224-B · verified" },
      ],
    },
    {
      title: "IN-PROCESS CHECKS",
      items: [
        { label: "Thickness · 3 samples", note: "Acceptance criteria attached" },
        { label: "Visual inspection", note: "Surface · station capture" },
        { label: "Torque check", note: "Fixture 2" },
      ],
    },
    {
      title: "BATCH RECORD",
      items: [
        {
          label: "Thickness reading",
          kind: "field",
          value: "41.2 µm · in spec",
          note: "Sealed 10:42 · P. Ndiaye",
        },
        { label: "Lot genealogy", note: "Consumed lots linked" },
        { label: "Release signature", kind: "approval", signer: "P. Ndiaye", state: "Signed", note: "21 CFR Part 11" },
      ],
    },
  ],
};

/* ============================================================ draft flow
 * Step rows in the Product Flows DB idiom, ready to ratify into Notion. */
export const MES_DRAFT_FLOWS: ProductFlow[] = [
  {
    id: "mes-d1",
    actor: "Shop Floor Operator",
    title: "Run the eTraveller (draft)",
    fullName:
      "Shop Floor Operator runs a work order through the eTraveller to a sealed batch record",
    description: DRAFT_NOTE,
    stations: [],
    outcomes: [],
    steps: [
      {
        index: 1,
        name: "Pick up the released work order from the queue",
        what: "The released work order lands on the operator's queue with the traveller, routing, and staged materials linked. Picked up from the queue rather than a printed packet at a shift-start huddle.",
        decision: "Is everything staged to start, or does the release need to be queried.",
        role: "Operator",
        primitives: ["Status-chasing"],
      },
      {
        index: 2,
        name: "Open the eTraveller with routing and the current SOP in context",
        what: "Opens the eTraveller. The routing step, the controlled work instruction at its current revision, and the lot context sit on the record; nothing is fetched from a binder or a shared drive.",
        decision: "Is this the right step and revision for the lot on the line.",
        role: "Operator",
        primitives: ["Errors", "Reconciliation"],
      },
      {
        index: 3,
        name: "Execute the control-plan checks as structured tasks",
        what: "Runs the inspection and control-plan checks as structured tasks with acceptance criteria attached. Each result is captured at the station as it happens, not transcribed later.",
        decision: "Does each reading pass its criteria, or does the step need a hold.",
        role: "Inspector",
        primitives: ["Errors"],
      },
      {
        index: 4,
        name: "Record batch data with evidence sealed to the lot",
        what: "Readings, consumed lots, and equipment land on the electronic batch record with operator and timestamp sealed to each entry. The record builds itself as the work happens instead of being assembled at the end.",
        decision: "Is the entry complete before the step closes.",
        role: "Recorder",
        primitives: ["Reconciliation", "Decision-rebuilding"],
      },
      {
        index: 5,
        name: "Complete the traveller and release with an electronic signature",
        what: "Completes the final step and signs the release with a regulated electronic signature. The sealed batch record closes with full genealogy; review-by-exception replaces the end-of-lot paper chase.",
        decision: "Is the record clean enough to release, or does an exception need review.",
        role: "Approver",
        primitives: ["Status-chasing", "Errors"],
      },
    ],
  },
];

/* ============================================================ modules
 * The modules section as camera work: five module tabs, five poses on the
 * SAME work order WO-9021 - genuinely one continuous record from release to
 * the sealed lot. One scene instance; tab changes pan the camera. */
export const MES_MODULE_ARCADE_CONFIGS: Record<string, ArcadeStepConfig> = {
  "work-order-management": {
    source: "MES modules · release queue",
    ghost: "Release",
    type: "Work Order",
    id: "#9021",
    title: "PRT-4412 housing · lot 224-B",
    status: "Released",
    actor: "automator",
    event: "Released the work order to line 2",
    eventDetail: "Traveller, routing, and staged materials linked · no printed packet",
    checklist: "ROUTING & SETUP",
    checklistItems: ["Routing step", "Materials staged"],
    focus: "queue",
    focusTitle: "Work orders",
    focusRows: [
      "WO-9021 · PRT-4412 housing · released",
      "Traveller attached · routing Rev C",
      "Materials staged · lot 224-B",
    ],
    focusAction: "Start traveller",
    ownershipNote: "Everything staged before the line starts",
    world: TRAVELLER_WORLD,
    queueTile: "Work orders",
  },
  etravellers: {
    source: "MES modules · traveller context",
    ghost: "Travel",
    type: "Work Order",
    id: "#9021",
    title: "PRT-4412 housing · lot 224-B",
    status: "In Process",
    actor: "You",
    event: "Opened the eTraveller at routing step 3",
    eventDetail: "The controlled work instruction at its current revision, on the record",
    checklist: "ROUTING & SETUP",
    checklistItems: ["Routing step", "Work instruction"],
    focus: "record",
    focusTitle: "Right step, right revision",
    focusRows: ["Step 3 of 8 · coating · line 2", "SOP-118 Rev D linked · current by construction"],
    focusAction: "Begin step",
    ownershipNote: "Nothing fetched from a binder",
    world: TRAVELLER_WORLD,
    checklistOpen: "ROUTING & SETUP",
  },
  "fai-control-plan-execution": {
    source: "MES modules · first article",
    ghost: "Approve",
    type: "Work Order",
    id: "#9021",
    title: "PRT-4412 housing · lot 224-B",
    status: "In Process",
    actor: "You",
    event: "Ran the first article against the control plan",
    eventDetail: "Criteria from the plan · disposition on the record before the run",
    checklist: "IN-PROCESS CHECKS",
    checklistItems: ["Thickness · 3 samples", "Torque check"],
    focus: "review",
    focusTitle: "First article · fixture 2",
    focusRows: [
      "FAI-52 · dimensions 12 of 12 in spec",
      "Control plan · coating step criteria",
      "Disposition · approved to run",
    ],
    focusAction: "Approve first article",
    focusAlts: ["Hold the line"],
    ownershipNote: "The run starts only on approval",
    world: TRAVELLER_WORLD,
    checklistOpen: "IN-PROCESS CHECKS",
  },
  "inspections-forms-checklists": {
    source: "MES modules · station capture",
    ghost: "Inspect",
    type: "Work Order",
    id: "#9021",
    title: "PRT-4412 housing · lot 224-B",
    status: "In Process",
    actor: "You",
    event: "Ran the in-process checks at the station",
    eventDetail: "Acceptance criteria attached to each task · captured as it happens",
    checklist: "IN-PROCESS CHECKS",
    checklistItems: ["Thickness · 3 samples", "Visual inspection", "Torque check"],
    focus: "tasks",
    focusTitle: "In-process checks",
    focusRows: [
      "Thickness · 3 samples · Station 2",
      "Visual inspection · surface",
      "Torque check · fixture 2",
    ],
    focusAction: "Capture results",
    ownershipNote: "A failed criterion holds the step",
    world: TRAVELLER_WORLD,
    checklistOpen: "IN-PROCESS CHECKS",
    checklistProgress: { "ROUTING & SETUP": 3, "IN-PROCESS CHECKS": 2, "BATCH RECORD": 0 },
  },
  "electronic-batch-lot-records": {
    source: "MES modules · the record builds itself",
    ghost: "Seal",
    type: "Work Order",
    id: "#9021",
    title: "PRT-4412 housing · lot 224-B",
    status: "In Process",
    actor: "You",
    event: "Entering the reading on the batch record",
    eventDetail: "Operator and timestamp seal to the entry · genealogy links as lots are consumed",
    checklist: "BATCH RECORD",
    checklistItems: ["Thickness reading", "Lot genealogy", "Release signature"],
    focus: "checklist",
    focusTitle: "The record builds as the work happens",
    focusRows: ["Nothing assembled at the end of the lot"],
    focusAction: "Seal entry",
    ownershipNote: "Review-by-exception, not a paper chase",
    world: TRAVELLER_WORLD,
    checklistOpen: "BATCH RECORD",
    checklistEntry: { section: "BATCH RECORD", item: "Thickness reading" },
  },
};

/* ============================================================ scenes */
export const MES_ARCADE_FLOW_CONFIGS: Record<string, ArcadeStepConfig[]> = {
  "mes-d1": [
    {
      source: "MES draft s1 · released to the queue",
      ghost: "Start",
      type: "Work Order",
      id: "#9021",
      title: "PRT-4412 housing · lot 224-B",
      status: "Released",
      actor: "automator",
      event: "Released the work order to line 2",
      eventDetail: "Traveller, routing, and staged materials linked · no printed packet",
      checklist: "ROUTING & SETUP",
      checklistItems: ["Routing step", "Work instruction", "Materials staged"],
      focus: "queue",
      focusTitle: "Work orders",
      focusRows: [
        "WO-9021 · PRT-4412 housing · released",
        "Traveller attached · routing Rev C",
        "Materials staged · lot 224-B",
      ],
      focusAction: "Start traveller",
      ownershipNote: "Query the release if staging is short",
      world: TRAVELLER_WORLD,
      queueTile: "Work orders",
      checklistProgress: { "ROUTING & SETUP": 1, "IN-PROCESS CHECKS": 0, "BATCH RECORD": 0 },
    },
    {
      source: "MES draft s2 · traveller in context",
      ghost: "Open",
      type: "Work Order",
      id: "#9021",
      title: "PRT-4412 housing · lot 224-B",
      status: "In Process",
      actor: "You",
      event: "Opened the eTraveller at routing step 3",
      eventDetail: "Controlled work instruction at its current revision, on the record",
      checklist: "ROUTING & SETUP",
      checklistItems: ["Routing step", "Work instruction"],
      focus: "record",
      focusTitle: "Right step, right revision",
      focusRows: ["Step 3 of 8 · coating · line 2", "SOP-118 Rev D linked · current by construction"],
      focusAction: "Begin step",
      ownershipNote: "Nothing fetched from a binder",
      world: TRAVELLER_WORLD,
      checklistOpen: "ROUTING & SETUP",
      checklistProgress: { "ROUTING & SETUP": 3, "IN-PROCESS CHECKS": 0, "BATCH RECORD": 0 },
    },
    {
      source: "MES draft s3 · control plan as tasks",
      ghost: "Check",
      type: "Work Order",
      id: "#9021",
      title: "PRT-4412 housing · lot 224-B",
      status: "In Process",
      actor: "You",
      event: "Ran the control-plan checks at the station",
      eventDetail: "Acceptance criteria attached to each task · captured as it happens",
      checklist: "IN-PROCESS CHECKS",
      checklistItems: ["Thickness · 3 samples", "Visual inspection", "Torque check"],
      focus: "tasks",
      focusTitle: "In-process checks",
      focusRows: [
        "Thickness · 3 samples · Station 2",
        "Visual inspection · surface",
        "Torque check · fixture 2",
      ],
      focusAction: "Capture results",
      ownershipNote: "A failed criterion holds the step",
      world: TRAVELLER_WORLD,
      checklistOpen: "IN-PROCESS CHECKS",
      checklistProgress: { "ROUTING & SETUP": 3, "IN-PROCESS CHECKS": 2, "BATCH RECORD": 0 },
    },
    {
      source: "MES draft s4 · the record builds itself",
      ghost: "Seal",
      type: "Work Order",
      id: "#9021",
      title: "PRT-4412 housing · lot 224-B",
      status: "In Process",
      actor: "You",
      event: "Entering the reading on the batch record",
      eventDetail: "Operator and timestamp seal to the entry · genealogy links as lots are consumed",
      checklist: "BATCH RECORD",
      checklistItems: ["Reading 41.2 µm · sealed 10:42 · PN", "Lot 224-B consumed · genealogy linked", "Equipment · coater 2 · verified"],
      focus: "checklist",
      focusTitle: "The record builds as the work happens",
      focusRows: ["Nothing assembled at the end of the lot", "Close step"],
      focusAction: "Seal entry",
      ownershipNote: "Nothing assembled at the end of the lot",
      world: TRAVELLER_WORLD,
      checklistOpen: "BATCH RECORD",
      checklistEntry: { section: "BATCH RECORD", item: "Thickness reading" },
      checklistProgress: { "ROUTING & SETUP": 3, "IN-PROCESS CHECKS": 3, "BATCH RECORD": 0 },
    },
    {
      source: "MES draft s5 · release under Part 11",
      ghost: "Release",
      type: "Work Order",
      id: "#9021",
      title: "PRT-4412 housing · lot 224-B",
      status: "Completed",
      actor: "You",
      event: "Signed the release on the sealed batch record",
      eventDetail: "Full genealogy closed with the lot · review-by-exception, not a paper chase",
      checklist: "BATCH RECORD",
      checklistItems: ["Entries sealed", "Lot genealogy", "Release signature"],
      focus: "signature",
      focusTitle: "Release lot 224-B",
      focusRows: ["Sealed batch record · 8 of 8 steps", "Genealogy complete"],
      focusAction: "Apply your signature",
      ownershipNote: "An exception would route to review instead",
      world: TRAVELLER_WORLD,
      checklistOpen: "BATCH RECORD",
      checklistProgress: { "ROUTING & SETUP": 3, "IN-PROCESS CHECKS": 3, "BATCH RECORD": 3 },
    },
  ],
};
