/* ============================================================================
 * customer-videos.ts - REAL customer videos for the Resources area.
 *
 * GENERATED from the Notion "Website Customer Videos" DB
 * (collection://7fdba279-eef5-45f7-bb80-7a1d02a1bb59, registry NDB-379) on
 * 2026-09-01: the top 50 rows with Web Use Approved = yes, Status = Live, and
 * a Wistia ID, ordered by Fav Count then attestation richness. Company/Role
 * are filled only where the DB attests them (Efco speakers carry no company
 * field by governance). Re-run the pull to refresh; do not hand-edit values.
 * ========================================================================== */

export type CustomerVideo = {
  slug: string;
  name: string;
  person: string;
  role?: string;
  company?: string;
  industry?: string;
  modules: string[];
  metrics: string[];
  persona?: string;
  duration: string;
  wistiaId: string;
  thumb?: string;
  description: string;
  fav: number;
};

export const CUSTOMER_VIDEOS: CustomerVideo[] = [
  { slug: "importance-of-approvals", name: "Importance of Approvals", person: "Wilson Lin", company: "Applechem", industry: "Cosmetics", modules: ["Approval Workflows", "Document Management"], metrics: [], persona: "Quality", duration: "2:10", wistiaId: "p0chdk1ja3", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/65cca258064710714d8db24a_AC-WL-N01%20-%20Importance%20of%20Approvals.png", description: "The video emphasizes the critical role of approvals in the operational workflow, showcasing how Unifize simplifies and speeds up the approval process. It highlights the platform's ability to streamline decision-making and ensure compliance, thereby enhancing overall efficiency and reducing time to market for new initiatives.", fav: 2 },
  { slug: "how-unifizes-no-code-configuration-speeds-up-implementation", name: "How Unifize's no-code configuration speeds up implementation", person: "Clarissa Archer", company: "Harmonic Bionics", industry: "Medical Devices", modules: [], metrics: ["Efficiency"], persona: "Quality", duration: "2:32", wistiaId: "pu02wkm0a4", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/657aabe7ab5569d13be763d0_HB-CA-07%20Speed%20up%20implementation%20with%20No-Code.png", description: "Clarissa Archer highlights adaptability as key in Harmonic Bionics' QMS selection. Unifize allowed them to tailor the software to their needs, avoiding the rigidity of traditional systems. The ability to make direct adjustments without external help was transformative, dramatically accelerating their processes.", fav: 2 },
  { slug: "how-unifize-makes-audits-easier", name: "How Unifize makes audits easier", person: "Jesse Kolstad", role: "Director of Quality", company: "Biovation Labs", industry: "Nutritional Supplements", modules: ["Supplier Quality", "Change Requests & Orders", "Audit Management"], metrics: [], persona: "Quality", duration: "2:38", wistiaId: "czpp4z5i75", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/657aa6c9f42c82e24d56b0e6_BL-JK-17%20Making%20audits%20easier.png", description: "Jesse Kolstad shares how Unifize revolutionized Biovation Labs' audit process. By capturing visual evidence directly into the platform, Unifize replaced manual notes and transcription with real-time documentation, reducing inefficiencies. Jesse highlights the clarity and context Unifize brings, transforming audits into a seamless, efficient experience.", fav: 1 },
  { slug: "how-unifize-speeds-up-approvals-around-product-specifications", name: "How Unifize speeds up approvals around product specifications", person: "Jesse Kolstad", role: "Director of Quality", company: "Biovation Labs", industry: "Nutritional Supplements", modules: [], metrics: [], persona: "Product Development", duration: "2:05", wistiaId: "x98prmmwgc", thumb: "https://cdn.prod.website-files.com/6475b503eba1a8c129c44339/657aa7453b3edd04b3ca138d_BL-JK-10%20Faster%20approvals%20on%20Product%20Specifications.png", description: "In this video, Jesse Kolstad of Biovation Labs discusses product specifications, from dosage forms to market presentations. He highlights Unifize's comprehensive role in managing, collaborating, and monitoring finished products, noting the transformative shift from traditional email approvals to Unifize's efficient system.", fav: 1 },
  { slug: "transitioning-from-an-existing-eqms-to-unifize", name: "Transitioning from an existing eQMS to Unifize", person: "Jesse Kolstad", role: "Director of Quality", company: "Biovation Labs", industry: "Nutritional Supplements", modules: [], metrics: [], persona: "Quality", duration: "0:44", wistiaId: "bnv5xz2fdn", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/657aa622021f925e8be76267_BL-JK-27%20Transitioning%20from%20existing%20QMS%20to%20Unifize.png", description: "Highlighting the transition from a traditional eQMS to Unifize, Jesse Kolstad lauds the platform's flexibility and advanced capabilities. With its user-friendly interface and transformative features, Unifize has brought about significant operational improvements at Biovation Labs.", fav: 1 },
  { slug: "wear-a-seatbelt-using-unifize-to-avoid-accidents-and-save-money", name: "Wear a seatbelt: using Unifize to avoid accidents and save money", person: "Jesse Kolstad", role: "Director of Quality", company: "Biovation Labs", industry: "Nutritional Supplements", modules: [], metrics: ["Visibility"], persona: "Quality", duration: "1:25", wistiaId: "zu0cjkzwyx", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/657aa57a71580a2988826dfd_BL-JK-34%20Wearing%20a%20seatbelt%20with%20Unifize.png", description: "Drawing a parallel with wearing a seatbelt, Jesse Kolstad elucidates how Unifize serves as a preventive tool, averting operational mishaps at Biovation Labs. Ensuring safety and compliance, Unifize's proactive features lead to significant cost savings by forestalling potential issues.", fav: 1 },
  { slug: "enabling-supplier-quality-on-unifize", name: "Enabling Supplier Quality on Unifize", person: "Clarissa Archer", company: "Harmonic Bionics", industry: "Medical Devices", modules: ["Supplier Corrective Actions (SCAR)", "Supplier Quality"], metrics: [], persona: "Quality", duration: "3:23", wistiaId: "44wjlgpqqt", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/657aa4ca021f925e8be65e62_HB-CA-17%20Enabling%20supplier%20quality.png", description: "Clarissa highlights how Unifize transformed supplier quality management, tackling challenges with non-conforming parts. She details how the platform documents and analyzes issues, identifies supplier performance trends, and drives impactful discussions. Unifize's capabilities enhance manufacturing efficiency and foster continuous quality improvements.", fav: 1 },
  { slug: "streamlining-processes-efficiently-in-a-small-company-with-unifize", name: "Streamlining processes efficiently in a small company with Unifize", person: "Wilson Lin", company: "Applechem", industry: "Cosmetics", modules: [], metrics: ["Visibility", "Accountability"], persona: "Quality", duration: "1:08", wistiaId: "zrvex9chm8", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/65cc9a2364fd225cd1fe3655_AC-WL-D02%20-%20Streamlining%20processes%20efficiently.png", description: "In this video, Wilson shares how Unifize revolutionized their small company by significantly enhancing visibility and accountability. Emphasizing it as a major quality of life improvement, they highlight the streamlined processes that now require less personnel involvement. Unifize eliminated the need for repetitive confirmations about document exchanges and validation steps, facilitating a smoother, more transparent workflow.", fav: 1 },
  { slug: "impact-of-lockdown-on-cosmetic-ingredient-manufacturers", name: "Impact of lockdown on cosmetic ingredient manufacturers", person: "Wilson Lin", company: "Applechem", industry: "Cosmetics", modules: [], metrics: [], persona: "Quality", duration: "3:29", wistiaId: "9a4qyvw2go", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/65cca133e82a7d5f33adaaa7_AC-WL-I02%20-%20Impact%20of%20lockdown%20on%20cosmetic%20ingredient.png", description: "This video discusses the significant challenges and adjustments faced by cosmetic ingredient manufacturers during the lockdown. It highlights how the industry navigated supply chain disruptions, shifts in consumer behavior, and the rapid pivot to digital platforms to maintain operations and meet demand.", fav: 1 },
  { slug: "why-should-a-cosmetic-ingredients-manufacturer-consider-using-unifize", name: "Why should a cosmetic ingredients manufacturer consider using Unifize", person: "Wilson Lin", company: "Applechem", industry: "Cosmetics", modules: [], metrics: [], persona: "Quality", duration: "1:18", wistiaId: "zsoq08beh9", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/65cca415b67040021d22745c_AC-WL-N09%20-%20Why%20should%20a%20cosmetic%20ingredients%20manufacturer.png", description: "Wilson discusses the specific benefits of Unifize for cosmetic ingredient manufacturers, focusing on the platform's role in enhancing collaboration, quality control, and regulatory compliance. The video underscores the importance of adopting advanced tools like Unifize in a competitive and highly regulated industry.", fav: 1 },
  { slug: "adopting-a-new-system-in-an-institutional-knowledge-based-shop-floor", name: "Adopting a new system in an institutional knowledge based shop floor", person: "Dave Anderson", industry: "Construction", modules: [], metrics: ["Efficiency"], persona: "Quality", duration: "0:46", wistiaId: "ishf3ekzxe", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/65e06af17e2748ba8174196d_E-DA-E05%20-%20Adopting%20a%20new%20system%20in%20an%20institutional.png", description: "Dave Anderson shares insights on the challenges and successes of implementing Unifize in a shop floor rich with institutional knowledge. He discusses the initial resistance to change and the transformative moment when team members begin to use Unifize, noting the ease and efficiency it brings to processes previously burdened by paperwork.", fav: 1 },
  { slug: "about-carol-and-her-role-at-efco", name: "About Carol and her role at Efco", person: "Carol Wilson", industry: "Construction", modules: [], metrics: [], persona: "Operations", duration: "0:44", wistiaId: "mu48o8bdrq", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/65d493f202936878628c7d5c_E-CW-I01%20-%20About%20Carol%20and%20her%20role%20at%20Efco.png", description: "Carol Wilson introduces herself as a senior purchaser at Efco, a company specializing in concrete forming systems for construction projects like bridges, houses, and parking garages. She oversees the procurement of all the steel required for Efco's forming systems, showcasing the complexity and importance of her role in the supply chain.", fav: 1 },
  { slug: "closing-the-loop-traceability-and-lot-tracking-using-unifize", name: "Closing the loop: traceability and lot tracking using Unifize", person: "Denis Machoka", company: "Harmonic Bionics", industry: "Medical Devices", modules: ["Electronic Lot Records", "Traceability Matrix", "Device Manufacturing Record", "Change Requests & Orders"], metrics: [], persona: "Quality", duration: "1:36", wistiaId: "wmltnu3t49", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/657aa8a2ab5569d13be4ac3f_HB-DM-18%20-%20Closing%20the%20loop_%20Traceability%20and%20lot%20tracking%20using%20Unifize.png", description: "Denis Machoka elucidates the intricate process of traceability and lot tracking at Harmonic Bionics, especially for their robotic devices. He details the meticulous tracing of parts, their consumption, and potential issues. Denis highlights how Unifize is instrumental in ensuring precise tracking and updating of materials consumed during device development.", fav: 1 },
  { slug: "comparing-unifize-vs-qt9", name: "Comparing Unifize vs QT9", person: "Dave Anderson", industry: "Construction", modules: [], metrics: ["Accountability"], persona: "Quality", duration: "3:22", wistiaId: "87uobmwy15", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/65e06a86d251a8b4a6d0da0a_E-DA-E03%20-%20Comparing%20Unifize%20vs%20QT9.png", description: "In this detailed comparison, Dave Anderson shares his candid insights on choosing Unifize over QT9 for quality management at Efco. He praises Unifize for its superior collaboration features, emphasizing how it promotes more personal and effective problem-solving through direct conversations and teamwork, unlike QT9's focus on mere record-keeping.", fav: 1 },
  { slug: "does-efco-comply-to-any-external-standards", name: "Does Efco comply to any external standards", person: "Dave Anderson", industry: "Construction", modules: [], metrics: [], persona: "Quality", duration: "0:58", wistiaId: "6i4p6moume", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/65e06bc3172c9586484d0ca0_E-DA-I03%20-%20Does%20Efco%20comply%20to%20any%20external%20standards.png", description: "Dave Anderson discusses Efco's approach to compliance standards, emphasizing that while not formally ISO certified, Efco's processes mirror ISO principles of record-keeping and operational consistency. He highlights Efco's adherence to ASTM standards for manufacturing and the training of welders to AWS standards.", fav: 1 },
  { slug: "how-smaller-groups-lead-to-70-faster-actions", name: "How smaller groups lead to 70% faster actions", person: "Dave Anderson", industry: "Construction", modules: [], metrics: ["Visibility", "Efficiency"], persona: "Quality", duration: "2:12", wistiaId: "1g31maaxtb", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/65e066b2141619f7da44774b_E-DA-D01%20-%20How%20smaller%20groups%20lead%20to%2070%25%20faster%20actions.png", description: "Dave Anderson from Efco shares how Unifize fostered smaller, more efficient discussion groups to swiftly address problems. By enabling seamless collaboration and record-keeping online, Unifize ensured that all stakeholders stayed informed and engaged, leading to a remarkable 70% improvement in action response times.", fav: 1 },
  { slug: "how-did-you-discover-unifize", name: "How did you discover Unifize", person: "Dave Anderson", industry: "Construction", modules: [], metrics: [], persona: "Quality", duration: "1:07", wistiaId: "juvzgx1rw6", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/65e06bf65f588c690884b2bc_E-DA-I04%20-%20How%20did%20you%20discover%20Unifize.png", description: "Dave Anderson shares the journey of discovering Unifize through a diligent search for a quality management system that could transition Efco from traditional, paper-based processes to a more efficient, cloud-based solution. The choice was made for Unifize largely due to its superior collaboration features over the competition.", fav: 1 },
  { slug: "improving-accountability", name: "Improving accountability", person: "Dave Anderson", industry: "Construction", modules: [], metrics: ["Accountability"], persona: "Quality", duration: "0:56", wistiaId: "p5ydx09ytw", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/65e06abc8a67042b63fa92b3_E-DA-E04%20-%20Improving%20accountability.png", description: "Dave Anderson emphasizes the unique approach Unifize brings to improving accountability within teams. By fostering direct, personal interactions over generic software notifications, Unifize encourages a culture where problems are not just flagged but solved collaboratively, in real time.", fav: 1 },
  { slug: "using-dashboards-on-unifize-to-make-management-review-meetings-easier", name: "Using dashboards on Unifize to make management review meetings easier", person: "Denis Machoka", company: "Harmonic Bionics", industry: "Medical Devices", modules: ["CAPAs"], metrics: [], persona: "Quality", duration: "1:32", wistiaId: "1dqmvmlupm", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/657aa8b3ab5569d13be4b919_HB-DM-17%20-%20Using%20dashboards%20on%20Unifize%20to%20make%20Management%20Review%20Meetings%20Easier.png", description: "Denis Machoka underscores the significance of Unifize's dashboards in streamlining management reviews. Highlighting the need for quick access to high-risk data points, he appreciates the platform's ability to present crucial insights on demand, contrasting it with the tedious method of manually collating data.", fav: 1 },
  { slug: "about-tedd-and-the-will-burt-company", name: "About Tedd and The Will-Burt Company", person: "Tedd Carr", role: "Director of Quality Control", company: "The Will-Burt Company", industry: "Manufacturing", modules: [], metrics: [], persona: "Quality", duration: "1:48", wistiaId: "4keakccbhz", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/657aa4634ecc369129c3cb4d_WB-TC-01-%20About%20Tedd%20and%20Will-Burt.png", description: "Tedd Carr, with four decades at The Will-Burt Company, oversees quality assurance across all departments, addressing diverse demands from sectors like aerospace and military. An employee-owned business with a century of innovation, Will-Burt specializes in emergency communications, payload elevation, and comprehensive manufacturing services.", fav: 0 },
  { slug: "accelerate-any-process-on-unifize-quotes-formulas-lot-release-raw-material-specs-and-approvals", name: "Accelerate any process on Unifize: quotes, formulas, lot release, raw material specs and approvals", person: "Jesse Kolstad", role: "Director of Quality", company: "Biovation Labs", industry: "Nutritional Supplements", modules: ["Approval Workflows"], metrics: [], persona: "Quality", duration: "3:00", wistiaId: "urt58k17lo", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/657aa6a298b7e7b4bafff08a_BL-JK-20%20Accelerate%20any%20process%20on%20Unifize.png", description: "In a regulated environment, Unifize streamlines processes from raw materials to product releases. Jesse Kolstad highlights its flexible approval workflows, instant quotation transfers, and collaboration features, emphasizing how Unifize instills confidence in approvals and accelerates operations at Biovation Labs.", fav: 0 },
  { slug: "breaking-organisational-silos-with-unifize-centralizing-knowledge-and-achieving-organisational-alignment", name: "Breaking organisational silos with Unifize", person: "Jesse Kolstad", role: "Director of Quality", company: "Biovation Labs", industry: "Nutritional Supplements", modules: ["Approval Workflows"], metrics: [], persona: "Quality", duration: "1:51", wistiaId: "nnlge3r2h0", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/657aa59fe86cb9333a97ef30_BL-JK-32%20Breaking%20organizational%20silos.png", description: "Jesse Kolstad emphasizes Unifize's instrumental role in dismantling organizational silos at Biovation Labs. By centralizing knowledge, the platform promotes a unified information hub, fostering organizational alignment and consistent collaboration, ensuring everyone operates in harmony.", fav: 0 },
  { slug: "about-michael-hogan-harmonic-bionics", name: "About Michael Hogan & Harmonic Bionics", person: "Michael Hogan", role: "Mechanical Engineer", company: "Harmonic Bionics", industry: "Medical Devices", modules: [], metrics: [], persona: "Operations", duration: "1:23", wistiaId: "2xwvmj0oxi", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/657aab9dbd1b9d834167ebc8_HB-MH-01%20-%20About%20HB%20and%20Michael.png", description: "Michael Hogan, a mechanical engineer at Harmonic Bionics, shares the company's beginnings as a group of grad students from the Renew Robotics Lab. Their passion for rehab robotics led to the creation of their flagship device, Harmony, designed to transform stroke recovery for patients.", fav: 0 },
  { slug: "about-jesse-kolstad", name: "About Jesse Kolstad", person: "Jesse Kolstad", role: "Director of Quality", company: "Biovation Labs", industry: "Nutritional Supplements", modules: ["Device Manufacturing Record"], metrics: [], persona: "Quality", duration: "1:53", wistiaId: "j6nacs70gx", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/657aa7c7ba30e9955527ff2f_BL-JK-02%20About%20Jesse%20Kolstad.png", description: "Jesse Kolstad, Director of Quality, Compliance, and Formulation at Biovation Labs, shares insights into his role and the company's operations in Salt Lake City. Part of the Wellful organization, Biovation manufactures capsules and tablets, collaborating with industry leaders in the dietary supplement sector.", fav: 0 },
  { slug: "building-a-knowledge-base-in-a-startup", name: "Building a knowledge base in a startup with Unifize", person: "Michael Hogan", role: "Mechanical Engineer", company: "Harmonic Bionics", industry: "Medical Devices", modules: ["Approval Workflows"], metrics: [], persona: "Product Development", duration: "3:26", wistiaId: "w25njzv4c6", thumb: "https://cdn.prod.website-files.com/6475b503eba1a8c129c44339/657aaad4fa4ad73ad90a3d5f_HB-MH-11%20-%20Building%20a%20knowledge%20base%20in%20a%20startup%20with%20Unifize.png", description: "Michael reflects on the unique dynamics of working in a small company, emphasizing the value of relationships with colleagues, suppliers, and clients. He contrasts the human-centric approaches of startups with the rigidity of large corporations, highlighting the balance between personal connections and structured workflows.", fav: 0 },
  { slug: "establishing-accountability-and-taking-faster-decisions-with-unifize", name: "Establishing accountability and taking faster decisions with Unifize", person: "Tedd Carr", role: "Director of Quality Control", company: "The Will-Burt Company", industry: "Manufacturing", modules: [], metrics: ["Accountability"], persona: "Quality", duration: "2:27", wistiaId: "uashgnl3ie", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/657aa43e70279c29852131ce_WB-TC-03-%20Establishing%20accountability%20and%20taking%20faster%20decisions%20with%20Unifize.png", description: "Tedd Carr shares how Unifize revolutionized quality management at The Will-Burt Company. Replacing a chaotic mix of emails and ad-hoc methods, Unifize consolidated five systems into one, introduced clear accountability, and reduced task completion times from weeks to days.", fav: 0 },
  { slug: "doing-95-internal-audits-remotely-with-unifize", name: "Doing 95% internal audits remotely with Unifize", person: "Tedd Carr", role: "Director of Quality Control", company: "The Will-Burt Company", industry: "Manufacturing", modules: [], metrics: [], persona: "Quality", duration: "0:57", wistiaId: "6lp5j555dy", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/657aa4251633a0298827aee6_WB-TC-04-%20Doing%2095%25%20internal%20audits%20remotely%20with%20Unifize.png", description: "Tedd Carr shares how The Will-Burt Company used Unifize to pivot 95% of internal audits to a remote format during travel restrictions. Unifize's conversation-driven platform ensured compliance without physical presence, demonstrating its strength in streamlining audit processes efficiently.", fav: 0 },
  { slug: "collaborating-with-vendors-using-unifize", name: "Collaborating with vendors using Unifize", person: "Michael Hogan", role: "Mechanical Engineer", company: "Harmonic Bionics", industry: "Medical Devices", modules: ["Design Control", "Design History File", "Document Management"], metrics: [], persona: "Product Development", duration: "2:45", wistiaId: "aphymhpqf8", thumb: "https://cdn.prod.website-files.com/6475b503eba1a8c129c44339/657aaac32576a0690299534e_HB-MH-12%20-%20Collaborating%20with%20%20vendors%20using%20Unifize.png", description: "Michael explains Harmonic Bionics' structured method for documenting design outputs, focusing on definitive files like step files and PDFs. His routine often includes handling quality notifications on Unifize, collaborating with vendors, and updating specifications, with Unifize streamlining vendor interactions.", fav: 0 },
  { slug: "how-unifize-ensures-everyone-is-trained-on-the-right-version-of-documents-and-sops", name: "How Unifize ensures everyone is trained on the right version of documents and SOPs", person: "Jesse Kolstad", role: "Director of Quality", company: "Biovation Labs", industry: "Nutritional Supplements", modules: ["Document Management", "Design Control", "Change Control"], metrics: [], persona: "Quality", duration: "2:27", wistiaId: "qayx823k6h", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/657aa71727b24f9d0cb1c49a_BL-JK-13%20Training%20on%20right%20documents%20and%20SOPs.png", description: "Jesse Kolstad highlights the complexities of document control in regulated industries, emphasizing the need for more than just maintaining master copies. With Unifize, he ensures the organization is well-trained and aligned with the latest documents and SOPs, promoting compliance and operational efficiency.", fav: 0 },
  { slug: "how-unifize-helped-reduce-60-000-of-material-cost-on-just-one-product", name: "How Unifize helped reduce $60,000 of material cost on just one product", person: "Jesse Kolstad", role: "Director of Quality", company: "Biovation Labs", industry: "Nutritional Supplements", modules: ["Document Management", "Risk Management", "Audit Management"], metrics: [], persona: "Product Development", duration: "3:51", wistiaId: "pyhr051l3i", thumb: "https://cdn.prod.website-files.com/6475b503eba1a8c129c44339/657aa72661d3b23b6026393a_BL-JK-12%20How%20Unifize%20helped%20reduce%20%2460%2C000%20of%20material%20cost%20in%20just%20one%20product.png", description: "Jesse Kolstad recounts a transformative shift at Biovation Labs enabled by Unifize. By analyzing ingredient performance and volumes, he streamlined 16 SKUs down to two, simplifying management and achieving significant cost savings.", fav: 0 },
  { slug: "how-unifize-improved-our-non-conformance-closure-time-by-75-within-the-first-month", name: "How Unifize improved our non-conformance closure time by 75% within the first month", person: "Tedd Carr", role: "Director of Quality Control", company: "The Will-Burt Company", industry: "Manufacturing", modules: ["NCs / Defects"], metrics: ["Efficiency"], persona: "Operations", duration: "1:55", wistiaId: "qp7129voyy", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/657aa37286a60f49a80b3549_WB-TC-10-%20How%20Unifize%20improved%20our%20issue%20closure%20time%20by%2075%25%20within%20the%20first%20month.png", description: "In just one month with Unifize, The Will-Burt Company reduced non-conformance closure times by 75%, from 4-5 weeks to 7.2 days. Customer complaint closure times also dropped by 60%, showcasing Unifize's transformative impact on efficiency and responsiveness in quality management.", fav: 0 },
  { slug: "how-unifize-already-had-everything-we-were-looking-for", name: "How Unifize already had everything we were looking for", person: "Tedd Carr", role: "Director of Quality Control", company: "The Will-Burt Company", industry: "Manufacturing", modules: [], metrics: [], persona: "Quality", duration: "1:24", wistiaId: "w433n4xy2q", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/657aa40851c70981a00cd556_WB-TC-06-%20How%20Unifize%20already%20had%20everything%20we%20were%20looking%20for.png", description: "The Will-Burt Company chose Unifize as their ideal QMS for its all-in-one capability, covering internal audits, non-conformances, customer feedback, and corrective actions. Tedd Carr highlights its flexibility to adapt to specific processes and ease of use, making it a standout, user-friendly solution.", fav: 0 },
  { slug: "how-unifize-helps-save-time", name: "How Unifize helps save time and get things done faster", person: "Michael Hogan", role: "Mechanical Engineer", company: "Harmonic Bionics", modules: [], metrics: [], duration: "1:52", wistiaId: "qjjpm5m1xl", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/657aab5ceeb9f695a7624d9e_HB-MH-06%20-%20How%20Unifize%20helps%20save%20time%20and%20get%20things%20done%20faster.png", description: "Michael from Harmonic Bionics praises Unifize for its transparency and coherence. He appreciates how the platform keeps everyone aligned with shared access to documents and chat histories. This unified understanding streamlines processes and allows Michael to focus on his core tasks, boosting productivity.", fav: 0 },
  { slug: "how-unifize-made-me-a-hero-in-my-company", name: "How Unifize made me a hero in my company", person: "Jesse Kolstad", role: "Director of Quality", company: "Biovation Labs", industry: "Nutritional Supplements", modules: [], metrics: ["Visibility"], persona: "Quality", duration: "2:35", wistiaId: "nxgignfqr8", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/657aa58ba5668b68371678f2_BL-JK-33%20How%20Unifize%20made%20me%20a%20hero.png", description: "Jesse Kolstad shares how Unifize has amplified his impact and recognition at Biovation Labs. The platform's transformative capabilities have led to substantial operational enhancements, making its users, like Jesse, pivotal contributors to the company's success.", fav: 0 },
  { slug: "how-i-reduced-mock-recall-time-down-to-18-minutes-with-unifize", name: "How I reduced mock recall time down to 18 minutes with Unifize", person: "Jesse Kolstad", role: "Director of Quality", company: "Biovation Labs", industry: "Nutritional Supplements", modules: ["Audit Management", "Mock Recall"], metrics: [], persona: "Quality", duration: "1:28", wistiaId: "rsqybjoajw", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/657aa6b692f5babdf3a7d8d9_BL-JK-19%20Reducing%20Mock%20Recall%20time%20down%20to%2018%20minutes.png", description: "Jesse Kolstad delves into mock recalls, often seen as a compliance burden. He recalls struggles with tight certification audit timelines and contrasts them with the transformative efficiency Unifize brings, revolutionizing the speed and ease of the mock recall process.", fav: 0 },
  { slug: "how-unifize-helps-quality-leaders-take-better-decisions-on-out-of-specs", name: "How Unifize helps quality leaders take better decisions on Out of Specs", person: "Jesse Kolstad", role: "Director of Quality", company: "Biovation Labs", industry: "Nutritional Supplements", modules: ["NCs / Defects"], metrics: [], persona: "Quality", duration: "5:44", wistiaId: "x2pjcg17d4", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/657aa7a69fc7c2766c6a1c44_BL-JK-05%20Taking%20better%20decisions%20on%20Out%20of%20Specs.png", description: "Jesse Kolstad recounts tackling a backlog of Out of Specification cases early at Biovation Labs. By analyzing existing processes, he emphasized understanding and data trending. Jesse highlights how Unifize brought clarity and enhanced decision-making, transforming the OOS process.", fav: 0 },
  { slug: "how-unifize-helped-reduce-our-training-time-and-costs", name: "How Unifize helped reduce our training time and costs", person: "Jesse Kolstad", role: "Director of Quality", company: "Biovation Labs", industry: "Nutritional Supplements", modules: ["Training"], metrics: [], persona: "Quality", duration: "1:43", wistiaId: "7sk4uqb9d3", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/657aa704727faaa188ffb1dc_BL-JK-14%20Reducing%20training%20time%20and%20costs.png", description: "Jesse Kolstad highlights how Unifize revolutionized Biovation Labs' training by linking SOPs, modules, roles, and employees for unmatched structure. He shares their innovative use of QR codes on RFID badges for instant training status verification, streamlining compliance checks and reducing training costs.", fav: 0 },
  { slug: "how-unifize-links-raw-materials-to-lots-formulas-and-finished-products", name: "How Unifize links raw materials to lots, formulas and finished products", person: "Jesse Kolstad", role: "Director of Quality", company: "Biovation Labs", industry: "Nutritional Supplements", modules: ["Traceability Matrix"], metrics: ["Traceability"], persona: "Product Development", duration: "0:48", wistiaId: "2hc3rzljvm", thumb: "https://cdn.prod.website-files.com/6475b503eba1a8c129c44339/657aa5be86f662a70903b6b5_BL-JK-30%20Linking%20raw%20material%20to%20lots%2C%20formulas%20and%20finished%20products.png", description: "Jesse Kolstad highlights Unifize's capability to seamlessly link raw materials to lots, formulas, and finished products. Providing a comprehensive view of the production process, Unifize ensures unparalleled traceability and accountability, enhancing production oversight at Biovation Labs.", fav: 0 },
  { slug: "how-unifize-helped-build-our-processes-efficiently-from-scratch", name: "How Unifize helped build our processes efficiently from scratch", person: "Jesse Kolstad", role: "Director of Quality", company: "Biovation Labs", industry: "Nutritional Supplements", modules: [], metrics: ["Efficiency"], persona: "Quality", duration: "5:38", wistiaId: "lmvii5x590", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/657aa779638ac257e6c42937_BL-JK-07%20Building%20processes%20from%20scratch.png", description: "Jesse Kolstad compares MasterControl's structured modules to Unifize's flexibility. Early in his career, he valued structured guidance, but as his expertise grew, he embraced Unifize's blank canvas approach for its ability to enable tailored and efficient process development.", fav: 0 },
  { slug: "starting-the-transformational-journey-with-unifize", name: "Starting the transformational journey with Unifize", person: "Jesse Kolstad", role: "Director of Quality", company: "Biovation Labs", industry: "Nutritional Supplements", modules: ["Supplier Quality", "Out of Spec"], metrics: [], persona: "Quality", duration: "2:51", wistiaId: "32og5b6ha9", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/657aa6023d43aa8b198b814a_BL-JK-29%20Starting%20the%20transformational%20journey%20with%20Unifize.png", description: "Detailing the transformational journey with Unifize, Jesse Kolstad emphasizes how the platform catalyzes a culture of continuous improvement. Unifize's adaptability and extensive capabilities underline its role as a game-changer in quality management at Biovation Labs.", fav: 0 },
  { slug: "problems-with-managing-quality-at-nutraceutical-companies", name: "Problems with managing quality at nutraceutical companies", person: "Jesse Kolstad", role: "Director of Quality", company: "Biovation Labs", industry: "Nutritional Supplements", modules: ["Supplier Quality", "Design History File", "Audit Management"], metrics: [], persona: "Quality", duration: "5:04", wistiaId: "qpl36rd9bh", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/657aa7913d43aa8b198cf9ab_BL-JK-06%20Problems%20with%20managing%20quality%20at%20neutraceutical%20companies.png", description: "Jesse Kolstad describes recurring challenges in quality management, from overloaded file cabinets to underutilized QMS systems. He emphasizes the need for observation and understanding before implementing reforms, showcasing his experienced, thoughtful approach to driving meaningful quality enhancements.", fav: 0 },
  { slug: "reducing-the-time-to-resolve-customer-complaints-on-unifize", name: "Reducing the time to resolve customer complaints on Unifize", person: "Jesse Kolstad", role: "Director of Quality", company: "Biovation Labs", industry: "Nutritional Supplements", modules: [], metrics: [], persona: "Quality", duration: "1:47", wistiaId: "796xicgn20", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/657aa6410a24dbc48e326e45_BL-JK-25%20Resolving%20customer%20complaints%20faster.png", description: "Jesse Kolstad highlights how Unifize expedites the resolution of customer complaints. Offering tools for rapid issue identification and fostering team collaboration, Unifize streamlines the complaint resolution process, ensuring accountability and efficiency in addressing customer concerns.", fav: 0 },
  { slug: "problems-with-other-eqms", name: "Problems I faced with other eQMS that Unifize solved", person: "Michael Hogan", role: "Mechanical Engineer", company: "Harmonic Bionics", industry: "Medical Devices", modules: [], metrics: [], persona: "Operations", duration: "1:54", wistiaId: "ml5sr2nkgy", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/657aab6be89977343b5f6a02_HB-MH-05%20-%20Problems%20I%20faced%20with%20other%20eQMS%20that%20Unifize%20solved.png", description: "Michael Hogan reflects on the inefficiencies of traditional QMS platforms, recalling how feedback on designs often took weeks. For agile startups like Harmonic Bionics, where speed is critical, he emphasizes the necessity of a responsive and interactive solution like Unifize.", fav: 0 },
  { slug: "product-lifecycle-management", name: "Managing product lifecycle with Unifize", person: "Michael Hogan", role: "Mechanical Engineer", company: "Harmonic Bionics", industry: "Medical Devices", modules: ["Supplier Quality", "Document Management"], metrics: [], persona: "Product Development", duration: "3:22", wistiaId: "x45yjndv0n", thumb: "https://cdn.prod.website-files.com/6475b503eba1a8c129c44339/657aab902576a069029a0fcd_HB-MH-03%20-%20Managing%20Product%20Lifecycle%20with%20Unifize.png", description: "Michael Hogan reflects on Harmonic Bionics' journey from a small team of college students to a structured organization. As they grew, the need for strong documentation and product management became clear, highlighting the vital role of an efficient QMS in streamlining operations.", fav: 0 },
  { slug: "reducing-lot-release-time-down-to-minutes-with-unifize", name: "Reducing lot release time down to minutes with Unifize", person: "Jesse Kolstad", role: "Director of Quality", company: "Biovation Labs", industry: "Nutritional Supplements", modules: ["Work Orders & Routing"], metrics: [], persona: "Quality", duration: "1:10", wistiaId: "c0rsc1e43v", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/657aa5690a24dbc48e31b9dc_BL-JK-35%20Reducing%20lot%20release%20times%20down%20to%20minutes.png", description: "Jesse Kolstad highlights how Unifize has dramatically curtailed lot release times at Biovation Labs. By optimizing the process, Unifize ensures lot releases are executed efficiently, reducing times to mere minutes.", fav: 0 },
  { slug: "taking-faster-decisions-on-non-conformances-with-unifize", name: "Taking faster decisions on non-conformances with Unifize", person: "Jesse Kolstad", role: "Director of Quality", company: "Biovation Labs", industry: "Nutritional Supplements", modules: ["NCs / Defects"], metrics: ["Efficiency"], persona: "Quality", duration: "1:25", wistiaId: "tbbwxj3z9h", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/657aa559a69a35189be414b7_BL-JK-36%20Taking%20faster%20decisions%20on%20Non%20Conformances.png", description: "Jesse Kolstad underscores the agility Unifize brings to decision-making on non-conformances at Biovation Labs. The platform fosters rapid issue identification and enhances collaboration for swift resolutions, ensuring effective and timely corrective actions.", fav: 0 },
  { slug: "near-instant-implementation-and-adoption-of-unifize", name: "Near instant implementation and adoption of Unifize", person: "Jesse Kolstad", role: "Director of Quality", company: "Biovation Labs", industry: "Nutritional Supplements", modules: ["Design Control", "Design History File"], metrics: [], persona: "Quality", duration: "4:27", wistiaId: "ji97greix3", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/657aa679e86cb9333a98a599_BL-JK-22%20Near%20instant%20implementation%20and%20adoption.png", description: "Jesse Kolstad lauds Unifize for its intuitive design and quick adoption. With tools that foster user engagement and autonomy, Unifize integrates smoothly into Biovation Labs' daily operations.", fav: 0 },
  { slug: "how-conversations-in-unifize-foster-better-collaboration", name: "How conversations in Unifize foster better collaboration", person: "Tedd Carr", role: "Director of Quality Control", company: "The Will-Burt Company", industry: "Manufacturing", modules: [], metrics: [], persona: "Quality", duration: "1:12", wistiaId: "irlu1r7dw3", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/657aa35b3b3edd04b3c6dd04_WB-TC-11-%20How%20conversations%20in%20Unifize%20foster%20better%20collaboration.png", description: "Tedd Carr praises Unifize's conversation-driven platform for revolutionizing collaboration at The Will-Burt Company. Following a refresher course, engagement surged, fostering organized information flow and seamless task progression across the team.", fav: 0 },
  { slug: "how-biovation-uses-unifize-to-create-traceability-and-take-better-decisions", name: "How Biovation uses Unifize to create traceability and take better decisions", person: "Jesse Kolstad", role: "Director of Quality", company: "Biovation Labs", industry: "Nutritional Supplements", modules: ["Traceability Matrix"], metrics: ["Traceability"], persona: "Quality", duration: "1:34", wistiaId: "drmp9dgyf9", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/655b2450483f4170e7208cae_BL-JK-08%20Creating%20traceability.png", description: "Jesse Kolstad highlights how Unifize is instrumental in managing ingredient specifications, formulating products, and monitoring trends. He underscores the platform's ability to seamlessly interconnect various stages of the production process, from ingredients to finished products.", fav: 0 },
  { slug: "hear-about-things-in-real-time-and-start-conversations-early-on-with-unifizes-mobile-capabilities", name: "Hear about things in real time with Unifize's mobile capabilities", person: "Tedd Carr", role: "Director of Quality Control", company: "The Will-Burt Company", industry: "Manufacturing", modules: [], metrics: [], persona: "Quality", duration: "1:14", wistiaId: "4kbdugixfw", thumb: "https://uploads-ssl.webflow.com/6475b503eba1a8c129c44339/657aa3d8057797efe0d1d4be_WB-TC-09-%20Hear%20about%20things%20in%20real%20time.png", description: "Tedd Carr highlights the impact of Unifize's mobile functionality at The Will-Burt Company. The cloud-based mobile app empowers the sales force to address customer concerns and initiate quality discussions in real time, enabling swift issue resolution for remote and traveling team members.", fav: 0 },
];

export const getVideo = (slug: string) => CUSTOMER_VIDEOS.find((v) => v.slug === slug);

/** industries actually present in the library, in first-seen order */
export const VIDEO_INDUSTRIES = [...new Set(CUSTOMER_VIDEOS.map((v) => v.industry).filter((i): i is string => !!i))];

/** personas actually present in the library */
export const VIDEO_PERSONAS = [...new Set(CUSTOMER_VIDEOS.map((v) => v.persona).filter((p): p is string => !!p))];
